# Generated by Django 5.0.14 on 2026-03-11 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=300, verbose_name='Полное название организации')),
                ('org_name_short', models.CharField(max_length=100, verbose_name='Краткое название')),
                ('director_name', models.CharField(help_text='Например: Фаттахова Ильгиза Ринатовича', max_length=200, verbose_name='ФИО директора (родит. падеж)')),
                ('director_initials', models.CharField(help_text='Например: И.Р. Фаттахов', max_length=50, verbose_name='Инициалы директора')),
                ('director_basis', models.CharField(default='Устава', max_length=100, verbose_name='Действует на основании')),
                ('unp', models.CharField(max_length=20, verbose_name='УНП')),
                ('okpo', models.CharField(blank=True, default='', max_length=30, verbose_name='ОКПО')),
                ('address', models.CharField(max_length=300, verbose_name='Юридический адрес')),
                ('account', models.CharField(max_length=60, verbose_name='Расчётный счёт (IBAN)')),
                ('bank', models.CharField(max_length=200, verbose_name='Название банка')),
                ('bank_branch', models.CharField(blank=True, default='', help_text='Например: ЦБУ №109', max_length=100, verbose_name='Отделение банка')),
                ('bic', models.CharField(max_length=20, verbose_name='БИК')),
                ('bank_city', models.CharField(default='г. Минск', max_length=50, verbose_name='Город банка')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон/факс')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['org_name_short'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Например: 01/05/2025', max_length=50, verbose_name='Номер договора')),
                ('date', models.DateField(verbose_name='Дата договора')),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=400, max_digits=10, verbose_name='Ежемесячная стоимость (руб.)')),
                ('service_desc', models.TextField(default='консультации (методическую помощь) по вопросам охраны труда', verbose_name='Описание услуг')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_date', models.DateField(verbose_name='Дата акта')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (руб.)')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='contracts.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Акт',
                'verbose_name_plural': 'Акты',
                'ordering': ['act_date'],
            },
        ),
    ]
