# Generated by Django 5.0.14 on 2026-03-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='number',
        ),
    ]
