# Generated by Django 5.0.14 on 2026-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_remove_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
        migrations.AddField(
            model_name='act',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
    ]
