# Generated by Django 5.2 on 2026-03-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_act_is_paid_act_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN (бел. руб.)'), ('USD', 'USD (доллар США)'), ('EUR', 'EUR (евро)')], default='BYN', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='monthly_amount',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=10, verbose_name='Ежемесячная стоимость'),
        ),
    ]
