# Generated by Django 5.0.14 on 2026-03-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_add_currency_to_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='Номер договора'),
        ),
    ]
