# Generated by Django 5.0.14 on 2026-03-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_fix_act_is_paid_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='print_envelope',
            field=models.BooleanField(default=True, help_text='Снять, если акты доставляются нарочным', verbose_name='Печать шильдиков'),
        ),
    ]
