# Generated by Django 5.0.14 on 2026-03-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_client_print_envelope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='director_basis',
            field=models.CharField(default='Устава', max_length=200, verbose_name='Действует на основании'),
        ),
    ]
