# Generated by Django 5.0.14 on 2026-05-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_extend_director_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='director_position',
            field=models.CharField(default='директор', help_text='Например: директор, председатель, генеральный директор', max_length=100, verbose_name='Должность подписанта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='director_initials',
            field=models.CharField(help_text='Например: И.Р. Фаттахов', max_length=50, verbose_name='Инициалы подписанта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='director_name',
            field=models.CharField(help_text='Например: Фаттахова Ильгиза Ринатовича', max_length=200, verbose_name='ФИО подписанта (родит. падеж)'),
        ),
    ]
