# Generated by Django 5.0.14 on 2026-05-24 15:00

from django.db import migrations


def fix_director_position(apps, schema_editor):
    Client = apps.get_model('contracts', 'Client')
    Client.objects.filter(director_position='директор').update(director_position='директора')


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_add_director_position'),
    ]

    operations = [
        migrations.RunPython(fix_director_position, migrations.RunPython.noop),
    ]
