# Generated by Django 5.0.14 on 2026-05-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_fix_director_position_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='director_position',
            field=models.CharField(default='директора', help_text='Родительный падеж: директора, председателя, генерального директора', max_length=100, verbose_name='Должность подписанта (родит. падеж)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
    ]
