# Generated by Django 5.2 on 2026-03-26 18:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True, verbose_name='Год')),
                ('expense_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Можно вводить как 20 или 0.20 для 20%.', max_digits=5, verbose_name='Ставка расходов')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Можно вводить как 20 или 0.20 для 20%.', max_digits=5, verbose_name='Ставка налога')),
                ('note', models.TextField(blank=True, default='', verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Налоговый год',
                'verbose_name_plural': 'Налоговые годы',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='TaxQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, '1 квартал'), (2, '2 квартал'), (3, '3 квартал'), (4, '4 квартал')], verbose_name='Квартал')),
                ('income_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма за квартал')),
                ('fszn_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ФСЗН за квартал')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='taxes.taxyear', verbose_name='Налоговый год')),
            ],
            options={
                'verbose_name': 'Налоговый квартал',
                'verbose_name_plural': 'Налоговые кварталы',
                'ordering': ['quarter'],
                'constraints': [models.UniqueConstraint(fields=('tax_year', 'quarter'), name='unique_tax_quarter_per_year')],
            },
        ),
    ]
