# Generated by Django 5.2 on 2026-03-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxyear',
            name='oked_1',
            field=models.CharField(default='74909', help_text='Справочно. В расчет не входит.', max_length=20, verbose_name='ОКЭД 1'),
        ),
        migrations.AddField(
            model_name='taxyear',
            name='oked_2',
            field=models.CharField(default='73120', help_text='Справочно. В расчет не входит.', max_length=20, verbose_name='ОКЭД 2'),
        ),
    ]
