# Generated by Django 5.0.14 on 2026-10-03 08:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_taxyear_oked_1_taxyear_oked_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], verbose_name='Месяц')),
                ('income_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма за месяц')),
                ('fszn_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ФСЗН за месяц')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='taxes.taxyear', verbose_name='Налоговый год')),
            ],
            options={
                'verbose_name': 'Налоговый месяц',
                'verbose_name_plural': 'Налоговые месяцы',
                'ordering': ['month'],
            },
        ),
        migrations.AddConstraint(
            model_name='taxmonth',
            constraint=models.UniqueConstraint(fields=('tax_year', 'month'), name='unique_tax_month_per_year'),
        ),
    ]
