# Generated by Django 5.0.14 on 2026-10-03 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0004_migrate_quarters_to_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tax', 'Налог'), ('fszn', 'ФСЗН')], default='tax', max_length=8, verbose_name='Вид')),
                ('period_month', models.PositiveSmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], help_text='Месяц, за который уплачено. Остаток считается нарастающим итогом.', verbose_name='За месяц')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Дата платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='taxes.taxyear', verbose_name='Налоговый год')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['period_month', 'paid_date', 'id'],
            },
        ),
    ]
