# Generated by Django 5.0.14 on 2026-10-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0005_add_tax_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayment',
            name='period_from',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], help_text='Только для платежа за несколько месяцев; иначе оставьте пустым.', null=True, verbose_name='С месяца'),
        ),
        migrations.AlterField(
            model_name='taxpayment',
            name='period_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], help_text='Месяц, за который уплачено (для диапазона — последний). Остаток считается нарастающим итогом.', verbose_name='За месяц (по месяц)'),
        ),
    ]
