# Generated by Django 5.0.14 on 2025-11-15 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0038_add_siz_wear_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=255, verbose_name='Наименование оборудования')),
                ('inventory_number', models.CharField(max_length=100, unique=True, verbose_name='Инвентарный номер')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Дата последнего ТО')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Дата следующего ТО')),
                ('maintenance_period_months', models.PositiveIntegerField(default=12, verbose_name='Периодичность ТО (месяцев)')),
                ('maintenance_history', models.JSONField(blank=True, default=list, help_text="Список записей: {'date': 'YYYY-MM-DD', 'comment': '...'}", verbose_name='История ТО')),
                ('maintenance_status', models.CharField(choices=[('operational', 'Исправно'), ('needs_maintenance', 'Требует ТО'), ('in_maintenance', 'На обслуживании'), ('out_of_order', 'Неисправно')], default='operational', max_length=20, verbose_name='Статус обслуживания')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadline_equipment', to='directory.department', verbose_name='Отдел')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_equipment', to='directory.organization', verbose_name='Организация')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadline_equipment', to='directory.structuralsubdivision', verbose_name='Структурное подразделение')),
            ],
            options={
                'verbose_name': 'ТО оборудования',
                'verbose_name_plural': 'ТО оборудования',
                'ordering': ['equipment_name'],
            },
        ),
        migrations.CreateModel(
            name='KeyDeadlineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_deadline_categories', to='directory.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Категория ключевых сроков',
                'verbose_name_plural': 'Категории ключевых сроков',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='KeyDeadlineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование мероприятия')),
                ('periodicity_months', models.PositiveIntegerField(help_text='Периодичность проведения мероприятия в месяцах', verbose_name='Периодичность (месяцев)')),
                ('current_date', models.DateField(help_text='Дата последнего/текущего проведения мероприятия', verbose_name='Дата текущего проведения')),
                ('next_date', models.DateField(blank=True, editable=False, help_text='Автоматически рассчитывается на основе текущей даты и периодичности', null=True, verbose_name='Дата следующего проведения')),
                ('responsible_person', models.CharField(blank=True, help_text='ФИО ответственного за проведение мероприятия', max_length=255, verbose_name='Ответственное лицо')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deadline_control.keydeadlinecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['next_date', 'name'],
            },
        ),
    ]
