# Generated by Django 5.0.14 on 2025-11-16 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0004_migrate_medical_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalexaminationtype',
            options={'ordering': ['name'], 'verbose_name': 'Вид медицинского осмотра', 'verbose_name_plural': 'Виды медицинских осмотров'},
        ),
        migrations.AlterUniqueTogether(
            name='harmfulfactor',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='medicalexaminationtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicalsettings',
            name='days_before_warning',
        ),
        migrations.AddField(
            model_name='medicalsettings',
            name='days_before_email',
            field=models.PositiveIntegerField(default=45, help_text='За сколько дней до окончания срока отправлять email-уведомление', verbose_name='Дней до уведомления по email'),
        ),
        migrations.AddField(
            model_name='medicalsettings',
            name='days_before_issue',
            field=models.PositiveIntegerField(default=30, help_text="За сколько дней до окончания срока менять статус на 'Нужно выдать направление'", verbose_name='Дней до выдачи направления'),
        ),
        migrations.AlterField(
            model_name='harmfulfactor',
            name='full_name',
            field=models.CharField(help_text='Полное наименование вредного производственного фактора', max_length=255, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='harmfulfactor',
            name='periodicity',
            field=models.PositiveIntegerField(help_text='Периодичность проведения медосмотра в месяцах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Периодичность (месяцы)'),
        ),
        migrations.AlterField(
            model_name='harmfulfactor',
            name='short_name',
            field=models.CharField(help_text='Краткое кодовое обозначение вредного фактора', max_length=50, verbose_name='Сокращенное наименование'),
        ),
        migrations.AlterField(
            model_name='medicalexaminationtype',
            name='name',
            field=models.CharField(help_text='Название вида медицинского осмотра', max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='harmfulfactor',
            unique_together={('short_name',)},
        ),
    ]
