# Generated by Django 5.0.14 on 2025-11-16 10:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0005_alter_medicalexaminationtype_options_and_more'),
        ('directory', '0040_remove_old_medical_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalsettings',
            options={'verbose_name': 'Настройки уведомлений', 'verbose_name_plural': 'Настройки уведомлений'},
        ),
        migrations.AlterField(
            model_name='medicalsettings',
            name='days_before_email',
            field=models.PositiveIntegerField(default=45, help_text='За сколько дней до наступления срока отправлять email-уведомление', verbose_name='Дней до напоминания на email'),
        ),
        migrations.AlterField(
            model_name='medicalsettings',
            name='days_before_issue',
            field=models.PositiveIntegerField(default=30, help_text="Через сколько дней до наступления срока выводить статус 'к выдаче'", verbose_name='Дней до отметки к выдаче'),
        ),
        migrations.CreateModel(
            name='MedicalReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_birth_date', models.DateField(help_text='Дата рождения сотрудника на момент выдачи', verbose_name='Дата рождения')),
                ('employee_address', models.TextField(help_text='Адрес проживания сотрудника на момент выдачи', verbose_name='Место проживания')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text='Дата выдачи направления', verbose_name='Дата выдачи')),
                ('document', models.FileField(blank=True, null=True, upload_to='medical_referrals/%Y/%m/', verbose_name='Документ направления')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_referrals', to='directory.employee', verbose_name='Сотрудник')),
                ('harmful_factors', models.ManyToManyField(blank=True, related_name='referrals', to='deadline_control.harmfulfactor', verbose_name='Вредные факторы')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_referrals', to=settings.AUTH_USER_MODEL, verbose_name='Кем выдано')),
            ],
            options={
                'verbose_name': 'Направление на медосмотр',
                'verbose_name_plural': 'Направления на медосмотры',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
