# Generated by Django 5.0.14 on 2025-11-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0006_add_medical_referral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalsettings',
            options={'verbose_name': 'Настройки медосмотров', 'verbose_name_plural': 'Настройки медосмотров'},
        ),
        migrations.AddField(
            model_name='medicalsettings',
            name='referral_template',
            field=models.FileField(blank=True, help_text='DOCX шаблон для генерации направлений. Если не указан, используется эталонный шаблон.', null=True, upload_to='document_templates/medical/', verbose_name='Шаблон направления на медосмотр'),
        ),
    ]
