# Generated by Django 5.0.14 on 2025-11-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0007_add_referral_template_setting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalexaminationnorm',
            options={'ordering': ['position_name', 'harmful_factor'], 'verbose_name': 'Вредный фактор профессии', 'verbose_name_plural': 'Вредные факторы по профессиям'},
        ),
        migrations.AlterField(
            model_name='employeemedicalexamination',
            name='date_completed',
            field=models.DateField(blank=True, help_text='Дата фактического прохождения медосмотра', null=True, verbose_name='Дата прохождения'),
        ),
        migrations.AlterField(
            model_name='employeemedicalexamination',
            name='next_date',
            field=models.DateField(blank=True, help_text='Плановая дата следующего медосмотра', null=True, verbose_name='Дата следующего медосмотра'),
        ),
    ]
