# Generated by Django 5.0.14 on 2025-11-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0008_make_medical_dates_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemedicalexamination',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='Если отмечено, медосмотр по этому фактору не требуется для данного сотрудника', verbose_name='Не требуется'),
        ),
    ]
