# Generated by Django 5.0.14 on 2025-11-19 13:43

import django.db.models.deletion
from django.db import migrations, models


def migrate_settings_to_organizations(apps, schema_editor):
    """
    Создает настройки для каждой организации на основе существующих глобальных настроек.
    """
    MedicalSettings = apps.get_model('deadline_control', 'MedicalSettings')
    Organization = apps.get_model('directory', 'Organization')

    # Получаем существующие глобальные настройки (если есть)
    global_settings = MedicalSettings.objects.first()

    if global_settings:
        # Копируем настройки для каждой организации
        organizations = Organization.objects.all()
        first_org = True

        for org in organizations:
            # Обновляем существующую запись или создаем новую
            if first_org and global_settings.organization_id is None:
                # Первой организации присваиваем глобальные настройки
                global_settings.organization = org
                global_settings.save()
                first_org = False
            else:
                # Для остальных создаем копии
                MedicalSettings.objects.create(
                    organization=org,
                    days_before_issue=global_settings.days_before_issue,
                    days_before_email=global_settings.days_before_email,
                    referral_template=global_settings.referral_template,
                )


def reverse_migration(apps, schema_editor):
    """
    Откат - удаляет все настройки кроме одной.
    """
    MedicalSettings = apps.get_model('deadline_control', 'MedicalSettings')
    # Оставляем только первую запись
    first_settings = MedicalSettings.objects.first()
    if first_settings:
        MedicalSettings.objects.exclude(pk=first_settings.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0009_add_is_disabled_to_medical_examination'),
        ('directory', '0041_add_document_generation_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalsettings',
            options={'ordering': ['organization__short_name_ru'], 'verbose_name': 'Настройки медосмотров', 'verbose_name_plural': 'Настройки медосмотров'},
        ),
        migrations.AddField(
            model_name='medicalsettings',
            name='organization',
            field=models.OneToOneField(blank=True, help_text='Организация, для которой применяются настройки', null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.organization', verbose_name='Организация'),
        ),
        migrations.RunPython(migrate_settings_to_organizations, reverse_migration),
    ]
