# Generated by Django 5.0.14 on 2025-11-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0010_add_organization_to_medical_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalsettings',
            name='referral_template',
            field=models.FileField(blank=True, help_text='Загрузите свой DOCX шаблон, если хотите использовать его вместо эталонного. Если не указан - будет использоваться эталонный шаблон системы.', null=True, upload_to='document_templates/medical/', verbose_name='Шаблон направления (необязательно)'),
        ),
    ]
