# Generated by Django 5.0.14 on 2025-11-19 14:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0011_update_referral_template_field_label'),
        ('directory', '0041_add_document_generation_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', help_text='Бэкенд для отправки email (обычно не требует изменения)', max_length=255, verbose_name='Email Backend')),
                ('email_host', models.CharField(blank=True, default='', help_text='Адрес SMTP сервера (например: smtp.gmail.com, smtp.yandex.ru)', max_length=255, verbose_name='SMTP сервер')),
                ('email_port', models.PositiveIntegerField(default=587, help_text='Порт SMTP сервера (587 для TLS, 465 для SSL, 25 для обычного)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='SMTP порт')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Использовать TLS шифрование (рекомендуется для порта 587)', verbose_name='Использовать TLS')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Использовать SSL шифрование (для порта 465)', verbose_name='Использовать SSL')),
                ('email_host_user', models.CharField(blank=True, default='', help_text='Email адрес для отправки (логин на SMTP сервере)', max_length=255, verbose_name='Email пользователь')),
                ('email_host_password', models.CharField(blank=True, default='', help_text='Пароль от email (для Gmail - пароль приложения)', max_length=255, verbose_name='Пароль')),
                ('default_from_email', models.EmailField(blank=True, default='', help_text="Email адрес, который будет указан в поле 'От кого'", max_length=254, verbose_name='Email отправителя')),
                ('is_active', models.BooleanField(default=True, help_text='Включить отправку email для этой организации', verbose_name='Активно')),
                ('recipient_emails', models.TextField(blank=True, default='', help_text='Email адреса получателей уведомлений (по одному на строку)', verbose_name='Email получателей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('organization', models.OneToOneField(help_text='Организация, для которой применяются настройки email', on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='directory.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Настройки Email (SMTP)',
                'verbose_name_plural': 'Настройки Email (SMTP)',
                'ordering': ['organization__short_name_ru'],
            },
        ),
    ]
