# Generated by Django 5.0.14 on 2025-12-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0012_add_email_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='instruction_journal_body',
            field=models.TextField(blank=True, default='Здравствуйте!\n\nНаправляем образец заполнения журнала повторных инструктажей для подразделения "{subdivision_name}".\n\nОрганизация: {organization_name}\nКоличество сотрудников: {employee_count}\nДата формирования: {date}\n\n---\nЭто автоматическое уведомление из системы управления охраной труда OT_online', help_text='Текст письма для отправки образца журнала. Доступные переменные: {subdivision_name}, {organization_name}, {employee_count}, {date}', verbose_name='Текст письма (образец журнала)'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='instruction_journal_subject',
            field=models.CharField(blank=True, default='Образец заполнения журнала инструктажей - {subdivision_name}', help_text='Тема письма для отправки образца журнала. Доступные переменные: {subdivision_name}, {organization_name}, {date}', max_length=255, verbose_name='Тема письма (образец журнала)'),
        ),
    ]
