# Generated by Django 5.0.14 on 2025-12-04 17:12

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0014_add_wysiwyg_to_email_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='instruction_journal_body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Здравствуйте!\n\nНаправляем образец заполнения журнала повторных инструктажей для подразделения "{subdivision_name}".\n\nОрганизация: {organization_name}\nКоличество сотрудников: {employee_count}\nДата формирования: {date}\n\n---\nЭто автоматическое уведомление из системы управления охраной труда OT_online', help_text='Текст письма для отправки образца журнала. Доступные переменные: {subdivision_name}, {organization_name}, {employee_count}, {date}', verbose_name='Текст письма (образец журнала)'),
        ),
    ]
