# Generated by Django 5.0.14 on 2025-12-05 06:42

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0015_migrate_to_ckeditor5'),
        ('directory', '0049_add_email_recipient_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Например: 'Образец журнала инструктажей'", max_length=100, unique=True, verbose_name='Название типа')),
                ('code', models.CharField(help_text="Уникальный код для использования в коде (например: 'instruction_journal')", max_length=50, unique=True, verbose_name='Код типа')),
                ('description', models.TextField(blank=True, help_text='Описание назначения этого типа шаблона', verbose_name='Описание')),
                ('available_variables', models.JSONField(default=dict, help_text='JSON с доступными переменными и их описанием', verbose_name='Доступные переменные')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Вид шаблона письма',
                'verbose_name_plural': 'Виды шаблонов писем',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='instruction_journal_body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='<p>Здравствуйте!</p>\n\n<p>Направляем образец заполнения журнала инструктажей.</p>\n\n<p><strong>Информация об инструктаже:</strong><br>\n<strong>Вид инструктажа:</strong> {instruction_type}<br>\n<strong>Дата проведения:</strong> {date}<br>\n<strong>Организация:</strong> {organization_name}<br>\n<strong>Подразделение:</strong> {subdivision_name}<br>\n<strong>Отдел:</strong> {department_name}<br>\n<strong>Количество сотрудников:</strong> {employee_count}</p>\n\n<p>Пожалуйста, проверьте образец и заполните журнал.</p>\n\n<p>---<br>\nЭто автоматическое уведомление из системы управления охраной труда OT_online</p>', help_text='Текст письма для отправки образца журнала. Доступные переменные: {organization_name}, {subdivision_name}, {department_name}, {date}, {instruction_type}, {instruction_reason}, {employee_count}', verbose_name='Текст письма (образец журнала)'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='instruction_journal_subject',
            field=models.CharField(blank=True, default='Образец журнала инструктажей - {subdivision_name}', help_text='Тема письма для отправки образца журнала. Доступные переменные: {organization_name}, {subdivision_name}, {department_name}, {date}, {instruction_type}, {instruction_reason}, {employee_count}', max_length=255, verbose_name='Тема письма (образец журнала)'),
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Произвольное название для удобства (например: 'Шаблон для ППП')", max_length=255, verbose_name='Название шаблона')),
                ('subject', models.CharField(help_text='Тема письма. Используйте переменные в фигурных скобках: {organization_name}, {date} и т.д.', max_length=255, verbose_name='Тема письма')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(help_text='Текст письма в формате HTML. Используйте переменные в фигурных скобках.', verbose_name='Текст письма')),
                ('is_active', models.BooleanField(default=True, help_text='Только активные шаблоны используются при отправке', verbose_name='Активен')),
                ('is_default', models.BooleanField(default=False, help_text='Использовать этот шаблон по умолчанию для данного типа и организации', verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='directory.organization', verbose_name='Организация')),
                ('template_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='deadline_control.emailtemplatetype', verbose_name='Тип шаблона')),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
                'ordering': ['organization', 'template_type', '-is_default', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization', 'template_type'), name='unique_default_template_per_org_type'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('organization', 'template_type', 'is_default')},
        ),
    ]
