# Generated by Django 5.0.14 on 2025-12-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0016_add_email_templates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsettings',
            options={'ordering': ['organization__short_name_ru'], 'verbose_name': '⚙️ Настройки Email (SMTP)', 'verbose_name_plural': '📧 Уведомления → Настройки Email'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['organization', 'template_type', '-is_default', 'name'], 'verbose_name': '📝 Шаблон письма', 'verbose_name_plural': '📧 Уведомления → Шаблоны писем'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplatetype',
            options={'ordering': ['name'], 'verbose_name': '📧 Вид шаблона письма', 'verbose_name_plural': '📧 Уведомления → Виды шаблонов'},
        ),
    ]
