# Generated by Django 5.0.14 on 2025-12-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0017_update_notifications_verbose_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsettings',
            name='instruction_journal_body',
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='instruction_journal_subject',
        ),
    ]
