# Generated by Django 5.0.14 on 2025-12-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0018_remove_instruction_journal_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsettings',
            options={'ordering': ['organization__short_name_ru'], 'verbose_name': '⚙️ Настройки Email (SMTP)', 'verbose_name_plural': '⚙️ Настройки Email (SMTP)'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['organization', 'template_type', '-is_default', 'name'], 'verbose_name': '📝 Шаблон письма', 'verbose_name_plural': '📝 Шаблоны писем'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplatetype',
            options={'ordering': ['name'], 'verbose_name': '📧 Вид шаблона письма', 'verbose_name_plural': '📧 Виды шаблонов'},
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='instruction_journal_recipients',
            field=models.TextField(blank=True, default='', help_text='Email адреса для рассылки образцов журналов повторных инструктажей. По одному на строку. Если пусто, используются общие получатели.', verbose_name='Email получателей (журналы инструктажей)'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='recipient_emails',
            field=models.TextField(blank=True, default='', help_text='Email адреса для общих уведомлений (медосмотры и т.д.). По одному на строку.', verbose_name='Email получателей (общие)'),
        ),
    ]
