# Generated by Django 5.0.14 on 2025-12-08 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0019_add_instruction_journal_recipients'),
        ('directory', '0049_add_email_recipient_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='instruction_journal_recipients',
            field=models.TextField(blank=True, default='', help_text='Email адреса для рассылки образцов журналов повторных инструктажей. По одному на строку. Если пусто, используются ТОЛЬКО получатели из подразделений (SubdivisionEmail + ответственные за ОТ), БЕЗ общих получателей.', verbose_name='Email получателей (журналы инструктажей)'),
        ),
        migrations.CreateModel(
            name='InstructionJournalSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('briefing_date', models.DateField(help_text='Дата проведения повторного инструктажа', verbose_name='Дата инструктажа')),
                ('briefing_type', models.CharField(default='Повторный', help_text='Повторный, Внеплановый и т.д.', max_length=100, verbose_name='Вид инструктажа')),
                ('briefing_reason', models.TextField(blank=True, default='', help_text='Причина проведения инструктажа', verbose_name='Причина проведения')),
                ('total_subdivisions', models.IntegerField(default=0, help_text='Общее количество подразделений в организации', verbose_name='Всего подразделений')),
                ('successful_count', models.IntegerField(default=0, verbose_name='Успешных отправок')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Ошибок отправки')),
                ('skipped_count', models.IntegerField(default=0, help_text='Пропущено (нет получателей или сотрудников)', verbose_name='Пропущено')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершено успешно'), ('partial', 'Завершено частично'), ('failed', 'Ошибка')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запуска')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_instruction_sends', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_send_logs', to='directory.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': '📧 Лог массовой рассылки',
                'verbose_name_plural': '📧 Логи массовых рассылок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructionJournalSendDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '✅ Отправлено'), ('failed', '❌ Ошибка'), ('skipped', '⏩ Пропущено')], max_length=20, verbose_name='Статус')),
                ('recipients', models.TextField(default='[]', help_text='JSON список email адресов: ["a@test.com", "b@test.com"]', verbose_name='Получатели (JSON)')),
                ('recipients_count', models.IntegerField(default=0, verbose_name='Количество получателей')),
                ('employees_count', models.IntegerField(default=0, help_text='Количество сотрудников в сгенерированном документе', verbose_name='Количество сотрудников')),
                ('email_subject', models.CharField(blank=True, default='', max_length=500, verbose_name='Тема письма')),
                ('skip_reason', models.CharField(blank=True, choices=[('no_recipients', 'Нет получателей'), ('no_employees', 'Нет сотрудников с инструкциями'), ('doc_generation_failed', 'Ошибка генерации документа'), ('template_not_found', 'Не найден шаблон письма'), ('email_send_failed', 'Ошибка отправки email')], default='', max_length=50, verbose_name='Причина пропуска')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Текст ошибки')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Дата и время фактической отправки письма', null=True, verbose_name='Дата отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_send_details', to='directory.structuralsubdivision', verbose_name='Подразделение')),
                ('send_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='deadline_control.instructionjournalsendlog', verbose_name='Лог рассылки')),
            ],
            options={
                'verbose_name': '📋 Деталь отправки',
                'verbose_name_plural': '📋 Детали отправок',
                'ordering': ['subdivision__name'],
            },
        ),
        migrations.AddIndex(
            model_name='instructionjournalsendlog',
            index=models.Index(fields=['organization', '-created_at'], name='deadline_co_organiz_d2bb47_idx'),
        ),
        migrations.AddIndex(
            model_name='instructionjournalsendlog',
            index=models.Index(fields=['initiated_by', '-created_at'], name='deadline_co_initiat_64188e_idx'),
        ),
        migrations.AddIndex(
            model_name='instructionjournalsendlog',
            index=models.Index(fields=['status'], name='deadline_co_status_abe4d5_idx'),
        ),
        migrations.AddIndex(
            model_name='instructionjournalsenddetail',
            index=models.Index(fields=['send_log', 'status'], name='deadline_co_send_lo_922a23_idx'),
        ),
        migrations.AddIndex(
            model_name='instructionjournalsenddetail',
            index=models.Index(fields=['subdivision'], name='deadline_co_subdivi_02c90d_idx'),
        ),
    ]
