# Generated by Django 5.0.14 on 2025-12-08 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0020_add_instruction_journal_send_log'),
        ('directory', '0049_add_email_recipient_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='keydeadlinecategory',
            name='email_template',
            field=models.ForeignKey(blank=True, help_text='Шаблон письма для автоматических уведомлений по этой категории', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_deadline_categories', to='deadline_control.emailtemplate', verbose_name='Шаблон email для рассылки'),
        ),
        migrations.CreateModel(
            name='KeyDeadlineSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('scheduled', '⏰ Плановая рассылка'), ('manual', '👤 Ручная отправка')], default='scheduled', max_length=20, verbose_name='Тип уведомления')),
                ('total_categories', models.IntegerField(default=0, help_text='Общее количество активных категорий в организации', verbose_name='Всего категорий')),
                ('overdue_items_count', models.IntegerField(default=0, help_text='Количество просроченных мероприятий', verbose_name='Просроченных мероприятий')),
                ('upcoming_items_count', models.IntegerField(default=0, help_text='Количество предстоящих мероприятий (в течение 30 дней)', verbose_name='Предстоящих мероприятий')),
                ('successful_count', models.IntegerField(default=0, verbose_name='Успешных отправок')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Ошибок отправки')),
                ('skipped_count', models.IntegerField(default=0, help_text='Пропущено (нет получателей или данных)', verbose_name='Пропущено')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершено успешно'), ('partial', 'Завершено частично'), ('failed', 'Ошибка')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запуска')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('email_template', models.ForeignKey(blank=True, help_text='Использованный шаблон email (если применим)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_deadline_logs', to='deadline_control.emailtemplate', verbose_name='Шаблон письма')),
                ('initiated_by', models.ForeignKey(blank=True, help_text='NULL для автоматических рассылок по расписанию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_key_deadline_sends', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_deadline_logs', to='directory.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': '⚙️ Лог рассылки уведомлений о ключевых мероприятиях',
                'verbose_name_plural': '⚙️ Логи рассылок уведомлений о ключевых мероприятиях',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyDeadlineSendDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '✅ Отправлено'), ('failed', '❌ Ошибка'), ('skipped', '⏭️ Пропущено')], max_length=20, verbose_name='Статус')),
                ('recipients', models.TextField(default='[]', help_text='JSON список email адресов: ["a@test.com", "b@test.com"]', verbose_name='Получатели (JSON)')),
                ('recipients_count', models.IntegerField(default=0, verbose_name='Количество получателей')),
                ('items_total', models.IntegerField(default=0, help_text='Общее количество мероприятий в категории', verbose_name='Всего мероприятий')),
                ('overdue_count', models.IntegerField(default=0, help_text='Количество просроченных мероприятий', verbose_name='Просроченных')),
                ('upcoming_count', models.IntegerField(default=0, help_text='Количество предстоящих мероприятий', verbose_name='Предстоящих')),
                ('email_subject', models.CharField(blank=True, default='', max_length=500, verbose_name='Тема письма')),
                ('skip_reason', models.CharField(blank=True, choices=[('no_recipients', 'Нет получателей'), ('no_items', 'Нет мероприятий для отправки'), ('template_not_found', 'Не найден шаблон письма'), ('email_send_failed', 'Ошибка отправки email')], default='', max_length=50, verbose_name='Причина пропуска')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Текст ошибки')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Дата и время фактической отправки письма', null=True, verbose_name='Дата отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_details', to='deadline_control.keydeadlinecategory', verbose_name='Категория')),
                ('send_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='deadline_control.keydeadlinesendlog', verbose_name='Лог рассылки')),
            ],
            options={
                'verbose_name': '📋 Деталь рассылки уведомления о ключевых мероприятиях',
                'verbose_name_plural': '📋 Детали рассылок уведомлений о ключевых мероприятиях',
                'ordering': ['category__name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalNotificationSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('scheduled', '⏰ Плановая рассылка'), ('manual', '👤 Ручная отправка')], default='scheduled', max_length=20, verbose_name='Тип уведомления')),
                ('no_date_count', models.IntegerField(default=0, help_text='Количество сотрудников без даты медосмотра', verbose_name='Без даты МО')),
                ('expired_count', models.IntegerField(default=0, help_text='Количество сотрудников с просроченным медосмотром', verbose_name='Просроченные МО')),
                ('upcoming_count', models.IntegerField(default=0, help_text='Количество сотрудников с предстоящим медосмотром', verbose_name='Предстоящие МО')),
                ('successful_count', models.IntegerField(default=0, verbose_name='Успешных отправок')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Ошибок отправки')),
                ('skipped_count', models.IntegerField(default=0, help_text='Пропущено (нет получателей или данных)', verbose_name='Пропущено')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершено успешно'), ('partial', 'Завершено частично'), ('failed', 'Ошибка')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запуска')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('email_template', models.ForeignKey(blank=True, help_text='Использованный шаблон email (если применим)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_notification_logs', to='deadline_control.emailtemplate', verbose_name='Шаблон письма')),
                ('initiated_by', models.ForeignKey(blank=True, help_text='NULL для автоматических рассылок по расписанию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_medical_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_notification_logs', to='directory.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': '🏥 Лог рассылки медицинских уведомлений',
                'verbose_name_plural': '🏥 Логи рассылок медицинских уведомлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalNotificationSendDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '✅ Отправлено'), ('failed', '❌ Ошибка'), ('skipped', '⏭️ Пропущено')], max_length=20, verbose_name='Статус')),
                ('recipients', models.TextField(default='[]', help_text='JSON список email адресов: ["a@test.com", "b@test.com"]', verbose_name='Получатели (JSON)')),
                ('recipients_count', models.IntegerField(default=0, verbose_name='Количество получателей')),
                ('employees_total', models.IntegerField(default=0, help_text='Общее количество сотрудников в уведомлении', verbose_name='Всего сотрудников')),
                ('no_date_count', models.IntegerField(default=0, verbose_name='Без даты МО')),
                ('expired_count', models.IntegerField(default=0, verbose_name='Просроченные МО')),
                ('upcoming_count', models.IntegerField(default=0, verbose_name='Предстоящие МО')),
                ('email_subject', models.CharField(blank=True, default='', max_length=500, verbose_name='Тема письма')),
                ('skip_reason', models.CharField(blank=True, choices=[('no_recipients', 'Нет получателей'), ('no_data', 'Нет данных для отправки'), ('template_not_found', 'Не найден шаблон письма'), ('email_send_failed', 'Ошибка отправки email')], default='', max_length=50, verbose_name='Причина пропуска')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Текст ошибки')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Дата и время фактической отправки письма', null=True, verbose_name='Дата отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('send_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='deadline_control.medicalnotificationsendlog', verbose_name='Лог рассылки')),
            ],
            options={
                'verbose_name': '📋 Деталь рассылки медицинского уведомления',
                'verbose_name_plural': '📋 Детали рассылок медицинских уведомлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='keydeadlinesendlog',
            index=models.Index(fields=['organization', '-created_at'], name='deadline_co_organiz_5c1c05_idx'),
        ),
        migrations.AddIndex(
            model_name='keydeadlinesendlog',
            index=models.Index(fields=['initiated_by', '-created_at'], name='deadline_co_initiat_a069cb_idx'),
        ),
        migrations.AddIndex(
            model_name='keydeadlinesendlog',
            index=models.Index(fields=['status'], name='deadline_co_status_cd326b_idx'),
        ),
        migrations.AddIndex(
            model_name='keydeadlinesendlog',
            index=models.Index(fields=['notification_type'], name='deadline_co_notific_ee5e54_idx'),
        ),
        migrations.AddIndex(
            model_name='keydeadlinesenddetail',
            index=models.Index(fields=['send_log', 'status'], name='deadline_co_send_lo_0d1c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='keydeadlinesenddetail',
            index=models.Index(fields=['category'], name='deadline_co_categor_ed650b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalnotificationsendlog',
            index=models.Index(fields=['organization', '-created_at'], name='deadline_co_organiz_42b481_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalnotificationsendlog',
            index=models.Index(fields=['initiated_by', '-created_at'], name='deadline_co_initiat_c6d9da_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalnotificationsendlog',
            index=models.Index(fields=['status'], name='deadline_co_status_331465_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalnotificationsendlog',
            index=models.Index(fields=['notification_type'], name='deadline_co_notific_147f29_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalnotificationsenddetail',
            index=models.Index(fields=['send_log', 'status'], name='deadline_co_send_lo_5b5c55_idx'),
        ),
    ]
