# Generated by Django 5.0.14 on 2025-12-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0021_add_email_template_to_key_deadline_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructionjournalsendlog',
            options={'ordering': ['-created_at'], 'verbose_name': '📧 Инструктажи', 'verbose_name_plural': '📧 Инструктажи'},
        ),
        migrations.AlterModelOptions(
            name='keydeadlinesendlog',
            options={'ordering': ['-created_at'], 'verbose_name': '⚙️ Ключевые события', 'verbose_name_plural': '⚙️ Ключевые события'},
        ),
        migrations.AlterModelOptions(
            name='medicalnotificationsendlog',
            options={'ordering': ['-created_at'], 'verbose_name': '🏥 Медосмотры', 'verbose_name_plural': '🏥 Медосмотры'},
        ),
    ]
