# Generated by Django 5.0.14 on 2025-12-10 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_medical_templates_to_reference(apps, schema_editor):
    """
    Миграция данных: преобразование медосмотровых шаблонов в эталонный.

    Логика:
    1. Находим тип шаблона 'medical_examination'
    2. Находим все шаблоны этого типа с is_default=True
    3. Выбираем первый шаблон как основу для эталона
    4. Создаём эталонный шаблон (organization=NULL, is_default=True)
    5. Удаляем старые организационные шаблоны медосмотров
    """
    EmailTemplate = apps.get_model('deadline_control', 'EmailTemplate')
    EmailTemplateType = apps.get_model('deadline_control', 'EmailTemplateType')

    # Находим тип шаблона
    try:
        medical_type = EmailTemplateType.objects.get(code='medical_examination')
    except EmailTemplateType.DoesNotExist:
        # Тип не создан - пропускаем миграцию
        print("[!] Tip shablona 'medical_examination' ne nayden, migratsiya propushchena")
        return

    # Находим все медосмотровые шаблоны
    medical_templates = EmailTemplate.objects.filter(
        template_type=medical_type,
        is_default=True
    ).order_by('id')

    if not medical_templates.exists():
        # Нет шаблонов для миграции
        print("[!] Medosmotrovye shablony ne naydeny, migratsiya propushchena")
        return

    # Берём первый шаблон как основу для эталона
    reference_base = medical_templates.first()

    # Сохраняем данные из шаблона-основы
    reference_subject = reference_base.subject
    reference_body = reference_base.body
    reference_created_by = reference_base.created_by

    # Удаляем старые организационные шаблоны медосмотров (СНАЧАЛА)
    deleted_count = medical_templates.delete()[0]

    # Создаём эталонный шаблон (ПОСЛЕ удаления)
    EmailTemplate.objects.create(
        organization=None,  # Эталонный шаблон
        template_type=medical_type,
        name='Эталонный шаблон медосмотров',
        subject=reference_subject,
        body=reference_body,
        is_active=True,
        is_default=True,
        created_by=reference_created_by
    )

    print(f"[OK] Sozdan etalonnyy shablon medosmotrov")
    print(f"[OK] Udaleno {deleted_count} organizatsionnykh shablonov medosmotrov")


def reverse_migration(apps, schema_editor):
    """
    Откат миграции: удаляем эталонный шаблон.

    ВНИМАНИЕ: организационные шаблоны НЕ восстанавливаются автоматически!
    Используйте backup БД для восстановления.
    """
    EmailTemplate = apps.get_model('deadline_control', 'EmailTemplate')
    EmailTemplateType = apps.get_model('deadline_control', 'EmailTemplateType')

    try:
        medical_type = EmailTemplateType.objects.get(code='medical_examination')
        # Удаляем эталонный шаблон
        deleted = EmailTemplate.objects.filter(
            template_type=medical_type,
            organization__isnull=True,
            is_default=True
        ).delete()
        print(f"[OK] Udalen etalonnyy shablon medosmotrov")
    except EmailTemplateType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0022_alter_instructionjournalsendlog_options_and_more'),
        ('directory', '0049_add_email_recipient_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emailtemplate',
            name='unique_default_template_per_org_type',
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Указывает, является ли шаблон эталонным для всех организаций. Эталонный шаблон не может быть привязан к организации.', verbose_name='Эталонный шаблон'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Организация, для которой предназначен шаблон. Если не указана, шаблон считается эталонным.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='directory.organization', verbose_name='Организация'),
        ),
        migrations.RunPython(
            migrate_medical_templates_to_reference,
            reverse_code=reverse_migration
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('organization__isnull', True)), fields=('template_type',), name='email_unique_default_template_per_type'),
        ),
    ]
