# Generated by Django 5.0.14 on 2025-12-12 07:11

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify
import re


def simplify_categories_forward(apps, schema_editor):
    """
    Миграция данных из старой структуры в новую:
    1. Обновляем категории (добавляем code, убираем organization)
    2. Переносим organization от категорий к мероприятиям
    3. Объединяем дублирующиеся категории
    """
    KeyDeadlineCategory = apps.get_model('deadline_control', 'KeyDeadlineCategory')
    KeyDeadlineItem = apps.get_model('deadline_control', 'KeyDeadlineItem')

    # Получаем все категории
    all_categories = list(KeyDeadlineCategory.objects.all().order_by('id'))

    if not all_categories:
        print("[INFO] Нет категорий для миграции")
        return

    print(f"[INFO] Найдено {len(all_categories)} категорий")

    # Группируем категории по имени
    categories_by_name = {}
    for cat in all_categories:
        if cat.name not in categories_by_name:
            categories_by_name[cat.name] = []
        categories_by_name[cat.name].append(cat)

    print(f"[INFO] Уникальных названий: {len(categories_by_name)}")

    # Обрабатываем каждую группу
    category_mapping = {}  # {old_cat_id: primary_cat_id}

    for idx, (cat_name, cat_group) in enumerate(categories_by_name.items(), start=1):
        # Берём первую категорию как основную
        primary_cat = cat_group[0]

        # Генерируем уникальный код
        base_code = re.sub(r'[^a-zA-Z0-9_]', '', slugify(cat_name, allow_unicode=True))
        if not base_code:
            base_code = f'category_{idx}'
        code = base_code[:50]

        # Проверяем уникальность кода
        counter = 1
        while KeyDeadlineCategory.objects.filter(code=code).exclude(id=primary_cat.id).exists():
            code = f'{base_code[:45]}_{counter}'
            counter += 1

        # Обновляем primary категорию
        primary_cat.code = code
        primary_cat.icon = '📋'
        primary_cat.sort_order = idx * 10
        primary_cat.organization = None  # Убираем привязку к организации
        primary_cat.save()

        print(f"[OK] Обновлена категория: {cat_name} (код: {code}, ID: {primary_cat.id})")

        # Переносим мероприятия из дублирующихся категорий
        for cat in cat_group:
            category_mapping[cat.id] = primary_cat.id

            # Получаем мероприятия этой категории
            items = KeyDeadlineItem.objects.filter(category_id=cat.id)

            for item in items:
                # Устанавливаем organization из категории
                item.organization_id = cat.organization_id
                # Перенацеливаем на primary категорию
                item.category_id = primary_cat.id
                # Сохраняем is_active от категории
                if hasattr(cat, 'is_active') and not cat.is_active:
                    item.is_active = False
                item.save()

        print(f"   - Перенесено мероприятий: {sum(KeyDeadlineItem.objects.filter(category_id=c.id).count() for c in cat_group)}")

    # Удаляем дублирующиеся категории
    to_delete = []
    for cat_name, cat_group in categories_by_name.items():
        if len(cat_group) > 1:
            # Удаляем все кроме первой
            to_delete.extend(cat_group[1:])

    if to_delete:
        deleted_ids = [cat.id for cat in to_delete]
        KeyDeadlineCategory.objects.filter(id__in=deleted_ids).delete()
        print(f"[OK] Удалено дублирующихся категорий: {len(to_delete)}")


def simplify_categories_backward(apps, schema_editor):
    """
    Откат миграции - восстанавливаем старую структуру
    """
    KeyDeadlineCategory = apps.get_model('deadline_control', 'KeyDeadlineCategory')
    KeyDeadlineItem = apps.get_model('deadline_control', 'KeyDeadlineItem')

    # Получаем все мероприятия
    items = KeyDeadlineItem.objects.all().select_related('category', 'organization')

    # Группируем по (category, organization)
    category_org_map = {}
    for item in items:
        key = (item.category.name, item.organization_id)
        if key not in category_org_map:
            # Создаём старую категорию (с organization)
            old_category = KeyDeadlineCategory.objects.create(
                name=item.category.name,
                organization_id=item.organization_id,
                description=item.category.description,
                is_active=True
            )
            category_org_map[key] = old_category

        # Обновляем item
        item.category = category_org_map[key]
        item.organization = None
        item.save()

    print(f"[OK] Откат завершен, восстановлено {len(category_org_map)} старых категорий")


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0023_convert_email_template_to_reference_pattern'),
        ('directory', '0049_add_email_recipient_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keydeadlinecategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Категория ключевых сроков', 'verbose_name_plural': 'Категории ключевых сроков'},
        ),
        migrations.AlterUniqueTogether(
            name='keydeadlinecategory',
            unique_together=set(),
        ),

        # ШАГ 1: Сделать старые поля nullable для безопасной миграции
        migrations.AlterField(
            model_name='keydeadlinecategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_deadline_categories', to='directory.organization', verbose_name='Организация'),
        ),

        # ШАГ 2: Добавить новые поля
        migrations.AddField(
            model_name='keydeadlinecategory',
            name='code',
            field=models.CharField(default='temp', help_text="Уникальный код для использования в коде (например: 'training_ot')", max_length=50, unique=True, verbose_name='Код категории'),
        ),
        migrations.AddField(
            model_name='keydeadlinecategory',
            name='icon',
            field=models.CharField(default='📋', help_text='Emoji иконка для отображения в интерфейсе', max_length=10, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='keydeadlinecategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения в списках (меньше = выше)', verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='keydeadlineitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Неактивные мероприятия не участвуют в рассылках уведомлений', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='keydeadlineitem',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_deadline_items', to='directory.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='keydeadlinecategory',
            name='name',
            field=models.CharField(help_text="Например: 'Обучение по ОТ', 'Инструктажи'", max_length=255, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='keydeadlineitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='deadline_control.keydeadlinecategory', verbose_name='Категория'),
        ),

        # ШАГ 3: Миграция данных
        migrations.RunPython(simplify_categories_forward, simplify_categories_backward),

        # ШАГ 4: Удалить старые поля
        migrations.RemoveField(
            model_name='keydeadlinecategory',
            name='email_template',
        ),
        migrations.RemoveField(
            model_name='keydeadlinecategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='keydeadlinecategory',
            name='organization',
        ),
    ]
