# Generated by Django 5.0.14 on 2025-12-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0024_simplify_key_deadline_step1'),
    ]

    operations = [
        migrations.AddField(
            model_name='keydeadlinesendlog',
            name='email_subject',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Тема письма'),
        ),
        migrations.AddField(
            model_name='keydeadlinesendlog',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Текст ошибки'),
        ),
        migrations.AddField(
            model_name='keydeadlinesendlog',
            name='recipients',
            field=models.TextField(default='[]', help_text='JSON список email адресов', verbose_name='Получатели (JSON)'),
        ),
        migrations.AddField(
            model_name='keydeadlinesendlog',
            name='recipients_count',
            field=models.IntegerField(default=0, verbose_name='Количество получателей'),
        ),
        migrations.AddField(
            model_name='keydeadlinesendlog',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время фактической отправки письма', null=True, verbose_name='Дата отправки'),
        ),
        migrations.DeleteModel(
            name='KeyDeadlineSendDetail',
        ),
    ]
