# Generated by Django 5.0.14 on 2025-12-12 12:07

import django.db.models.deletion
from django.db import migrations, models


def migrate_data_forward(apps, schema_editor):
    """
    Переносим данные из старой структуры в новую:
    1. Для каждого Item переносим organization из Item в Category
    2. Берем periodicity_months из первого Item в категории
    3. Создаем новые категории с привязкой к организациям
    """
    KeyDeadlineCategory = apps.get_model('deadline_control', 'KeyDeadlineCategory')
    KeyDeadlineItem = apps.get_model('deadline_control', 'KeyDeadlineItem')

    print("[INFO] Начинаем миграцию данных ключевых сроков...")

    # Получаем все мероприятия
    items = KeyDeadlineItem.objects.all().select_related('category')

    if not items.exists():
        print("[INFO] Нет мероприятий для миграции")
        return

    # Словарь для сопоставления (old_category_id, organization_id) -> new_category
    category_mapping = {}

    for item in items:
        old_category = item.category
        organization_id = getattr(item, 'organization_id', None)

        if not organization_id:
            print(f"[WARNING] Мероприятие '{item.name}' не имеет организации, пропускаем")
            continue

        # Ключ для поиска/создания категории
        key = (old_category.id, organization_id)

        if key not in category_mapping:
            # Ищем существующую категорию или создаем новую
            new_category, created = KeyDeadlineCategory.objects.get_or_create(
                organization_id=organization_id,
                name=old_category.name,
                defaults={
                    'periodicity_months': getattr(item, 'periodicity_months', 12),
                    'icon': old_category.icon,
                }
            )

            if created:
                print(f"[OK] Создана категория: {new_category.name} для организации ID {organization_id}")
            else:
                # Обновляем periodicity если еще не установлена
                if not new_category.periodicity_months:
                    new_category.periodicity_months = getattr(item, 'periodicity_months', 12)
                    new_category.save()

            category_mapping[key] = new_category

        # Перенацеливаем item на новую категорию
        item.category = category_mapping[key]
        item.save()

    # Удаляем старые категории без organization
    old_categories = KeyDeadlineCategory.objects.filter(organization__isnull=True)
    count = old_categories.count()
    if count > 0:
        old_categories.delete()
        print(f"[OK] Удалено {count} старых категорий без организации")

    print(f"[OK] Миграция завершена. Обработано {items.count()} мероприятий")


def migrate_data_backward(apps, schema_editor):
    """
    Откат миграции - восстанавливаем старую структуру
    """
    print("[INFO] Откат миграции не реализован - данные останутся в новой структуре")


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0025_remove_key_deadline_send_detail'),
        ('directory', '0049_add_email_recipient_system'),
    ]

    operations = [
        # Сначала добавляем новые поля
        migrations.AddField(
            model_name='keydeadlinecategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_deadline_categories', to='directory.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='keydeadlinecategory',
            name='periodicity_months',
            field=models.PositiveIntegerField(blank=True, help_text='Периодичность проведения мероприятий этой категории в месяцах', null=True, verbose_name='Периодичность (месяцев)'),
        ),
        migrations.AlterField(
            model_name='keydeadlinecategory',
            name='name',
            field=models.CharField(help_text="Например: 'Повторный инструктаж', 'Аттестация рабочих мест'", max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='keydeadlineitem',
            name='current_date',
            field=models.DateField(help_text='Дата последнего/текущего проведения мероприятия', verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='keydeadlineitem',
            name='name',
            field=models.CharField(help_text="Например: 'Испытание лестниц на складе'", max_length=500, verbose_name='Наименование мероприятия'),
        ),
        migrations.AlterField(
            model_name='keydeadlineitem',
            name='next_date',
            field=models.DateField(blank=True, editable=False, help_text='Автоматически рассчитывается на основе даты проведения и периодичности категории', null=True, verbose_name='Дата следующего проведения'),
        ),
        migrations.AlterField(
            model_name='keydeadlineitem',
            name='responsible_person',
            field=models.CharField(blank=True, help_text='ФИО или email ответственного за проведение мероприятия', max_length=255, verbose_name='Ответственное лицо'),
        ),

        # Миграция данных
        migrations.RunPython(migrate_data_forward, migrate_data_backward),

        # Удаляем старые поля
        migrations.RemoveField(
            model_name='keydeadlineitem',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='keydeadlineitem',
            name='periodicity_months',
        ),
        migrations.RemoveField(
            model_name='keydeadlinecategory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='keydeadlinecategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='keydeadlinecategory',
            name='sort_order',
        ),

        # Обновляем Meta
        migrations.AlterModelOptions(
            name='keydeadlinecategory',
            options={'ordering': ['organization', 'name'], 'verbose_name': 'Категория ключевых сроков', 'verbose_name_plural': 'Категории ключевых сроков'},
        ),
        migrations.AlterUniqueTogether(
            name='keydeadlinecategory',
            unique_together={('organization', 'name')},
        ),
    ]
