# Generated by Django 5.0.14 on 2025-12-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0026_refactor_key_deadline_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keydeadlinecategory',
            options={'ordering': ['organization', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': '📋 Категории (справочник)'},
        ),
        migrations.AlterModelOptions(
            name='keydeadlineitem',
            options={'ordering': ['next_date', 'name'], 'verbose_name': 'Ключевой срок', 'verbose_name_plural': '📅 Ключевые сроки'},
        ),
    ]
