# Generated by Django 5.0.14 on 2025-12-12 12:54

import django.db.models.deletion
from django.db import migrations, models


def migrate_data_forward(apps, schema_editor):
    """
    Переносим данные:
    1. organization из category в item
    2. Удаляем дублирующиеся категории, оставляя по одной
    """
    KeyDeadlineCategory = apps.get_model('deadline_control', 'KeyDeadlineCategory')
    KeyDeadlineItem = apps.get_model('deadline_control', 'KeyDeadlineItem')

    print("[INFO] Начинаем миграцию к справочным категориям...")

    # 1. Переносим organization в items
    items = KeyDeadlineItem.objects.all().select_related('category')
    for item in items:
        if item.category and hasattr(item.category, 'organization_id'):
            item.organization_id = item.category.organization_id
            item.save()
            print(f"[OK] Мероприятие '{item.name}' -> организация ID {item.organization_id}")

    # 2. Объединяем дублирующиеся категории
    category_map = {}  # name -> первая категория с таким именем
    categories_to_delete = []

    for category in KeyDeadlineCategory.objects.all():
        if category.name not in category_map:
            # Первая категория с таким именем - оставляем
            category_map[category.name] = category
            print(f"[OK] Оставляем категорию: {category.name}")
        else:
            # Дубликат - переносим мероприятия на первую категорию
            canonical_category = category_map[category.name]
            items_to_update = KeyDeadlineItem.objects.filter(category=category)
            count = items_to_update.count()
            if count > 0:
                items_to_update.update(category=canonical_category)
                print(f"[OK] Перенесено {count} мероприятий с дубликата '{category.name}' на каноническую")
            categories_to_delete.append(category.id)

    # Удаляем дубликаты
    if categories_to_delete:
        KeyDeadlineCategory.objects.filter(id__in=categories_to_delete).delete()
        print(f"[OK] Удалено {len(categories_to_delete)} дублирующихся категорий")

    print(f"[OK] Миграция завершена. Осталось {len(category_map)} уникальных категорий")


def migrate_data_backward(apps, schema_editor):
    """Откат не реализован"""
    print("[INFO] Откат миграции не реализован")


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0027_update_verbose_names'),
        ('directory', '0049_add_email_recipient_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keydeadlinecategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': '📋 Категории (справочник)'},
        ),
        migrations.AlterUniqueTogether(
            name='keydeadlinecategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='keydeadlineitem',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_deadline_items', to='directory.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='keydeadlineitem',
            name='periodicity_months',
            field=models.PositiveIntegerField(blank=True, help_text='Переопределяет периодичность из категории. Если пусто - берется из категории', null=True, verbose_name='Срок проведения (месяцев)'),
        ),
        migrations.AlterField(
            model_name='keydeadlinecategory',
            name='name',
            field=models.CharField(help_text="Например: 'Повторный инструктаж', 'Аттестация рабочих мест'", max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='keydeadlinecategory',
            name='periodicity_months',
            field=models.PositiveIntegerField(blank=True, help_text='Периодичность по умолчанию для мероприятий этой категории', null=True, verbose_name='Периодичность (месяцев)'),
        ),
        migrations.AlterField(
            model_name='keydeadlineitem',
            name='next_date',
            field=models.DateField(blank=True, editable=False, help_text='Автоматически рассчитывается на основе даты проведения и периодичности', null=True, verbose_name='Дата следующего проведения'),
        ),

        # Миграция данных
        migrations.RunPython(migrate_data_forward, migrate_data_backward),

        migrations.RemoveField(
            model_name='keydeadlinecategory',
            name='organization',
        ),

        # Добавляем unique constraint ПОСЛЕ удаления дубликатов
        migrations.AlterField(
            model_name='keydeadlinecategory',
            name='name',
            field=models.CharField(help_text="Например: 'Повторный инструктаж', 'Аттестация рабочих мест'", max_length=255, unique=True, verbose_name='Название категории'),
        ),
    ]
