# Generated by Django 5.0.14 on 2025-12-20 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0028_restructure_to_reference_categories'),
        ('directory', '0051_add_equipment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Лестница, Погрузчик, Автомобиль', max_length=100, unique=True, verbose_name='Название типа оборудования')),
                ('default_maintenance_period_months', models.PositiveIntegerField(default=12, help_text='Стандартная периодичность технического обслуживания для данного типа оборудования', verbose_name='Периодичность ТО по умолчанию (месяцев)')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о типе оборудования', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные типы не отображаются при выборе', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationKeyDeadline',
            fields=[
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': '📅 Ключевые сроки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('directory.organization',),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(blank=True, help_text='Выберите тип оборудования для автоматической подстановки периодичности ТО', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_items', to='deadline_control.equipmenttype', verbose_name='Тип оборудования'),
        ),
    ]
