# Generated by Django 5.0.14 on 2025-12-25 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0030_populate_equipment_types'),
        ('directory', '0054_convert_document_type_to_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentJournalSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(help_text='Дата, указанная в журнале осмотра', verbose_name='Дата осмотра')),
                ('total_subdivisions', models.IntegerField(default=0, verbose_name='Всего подразделений')),
                ('successful_count', models.IntegerField(default=0, verbose_name='Успешно отправлено')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Ошибок отправки')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='Пропущено')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершено успешно'), ('partial', 'Завершено частично'), ('failed', 'Ошибка')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_send_logs', to='deadline_control.equipmenttype', verbose_name='Тип оборудования')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_journal_send_logs', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор отправки')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_journal_send_logs', to='directory.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': '?? Журнал оборудования (рассылка)',
                'verbose_name_plural': '?? Журналы оборудования (рассылки)',
                'ordering': ['-created_at'],
                'db_table': 'deadline_control_equipment_journal_send_log',
            },
        ),
        migrations.CreateModel(
            name='EquipmentJournalSendDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '? Отправлено'), ('failed', '? Ошибка'), ('skipped', '?? Пропущено')], max_length=20, verbose_name='Статус')),
                ('recipients', models.TextField(default='[]', help_text='Список email адресов в формате JSON', verbose_name='Получатели (JSON)')),
                ('recipients_count', models.IntegerField(default=0, verbose_name='Количество получателей')),
                ('equipment_count', models.IntegerField(default=0, verbose_name='Количество оборудования')),
                ('email_subject', models.CharField(blank=True, max_length=500, verbose_name='Тема письма')),
                ('skip_reason', models.CharField(blank=True, choices=[('no_recipients', 'Нет получателей'), ('no_equipment', 'Нет оборудования данного типа'), ('doc_generation_failed', 'Ошибка генерации документа'), ('template_not_found', 'Не найден шаблон письма'), ('email_send_failed', 'Ошибка отправки email')], max_length=50, verbose_name='Причина пропуска')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('send_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='deadline_control.equipmentjournalsendlog', verbose_name='Лог рассылки')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_journal_send_details', to='directory.structuralsubdivision', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': '?? Деталь рассылки журнала',
                'verbose_name_plural': '?? Детали рассылок журналов',
                'ordering': ['subdivision__name'],
                'db_table': 'deadline_control_equipment_journal_send_detail',
            },
        ),
    ]
