# Generated by Django 5.0.14 on 2025-12-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0031_add_equipment_journal_send_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='load_capacity_kg',
            field=models.PositiveIntegerField(blank=True, help_text='Заполняется для грузовых тележек', null=True, verbose_name='Грузоподъемность (кг)'),
        ),
    ]
