# Generated by Django 5.0.14 on 2026-01-01 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0032_add_equipment_load_capacity'),
        ('directory', '0059_remove_document_email_send_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeemedicalexamination',
            options={'ordering': ['-date_completed', 'employee'], 'verbose_name': '🏥 Медосмотр сотрудника', 'verbose_name_plural': '🏥 Медосмотры сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['equipment_name'], 'verbose_name': '⚙️ ТО оборудования', 'verbose_name_plural': '⚙️ ТО оборудования'},
        ),
        migrations.AlterModelOptions(
            name='equipmentjournalsenddetail',
            options={'ordering': ['subdivision__name'], 'verbose_name': '📋 Деталь рассылки журнала', 'verbose_name_plural': '📋 Детали рассылок журналов'},
        ),
        migrations.AlterModelOptions(
            name='equipmentjournalsendlog',
            options={'ordering': ['-created_at'], 'verbose_name': '📧 Журнал оборудования (рассылка)', 'verbose_name_plural': '📧 Журналы оборудования (рассылки)'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'ordering': ['name'], 'verbose_name': '🔧 Тип оборудования', 'verbose_name_plural': '🔧 Типы оборудования'},
        ),
        migrations.AlterModelOptions(
            name='harmfulfactor',
            options={'ordering': ['short_name'], 'verbose_name': '☠️ Вредный фактор', 'verbose_name_plural': '☠️ Вредные факторы'},
        ),
        migrations.AlterModelOptions(
            name='keydeadlinecategory',
            options={'ordering': ['name'], 'verbose_name': '📋 Категория', 'verbose_name_plural': '📋 Категории (справочник)'},
        ),
        migrations.AlterModelOptions(
            name='keydeadlineitem',
            options={'ordering': ['next_date', 'name'], 'verbose_name': '📅 Ключевой срок', 'verbose_name_plural': '📅 Ключевые сроки'},
        ),
        migrations.AlterModelOptions(
            name='medicalexaminationnorm',
            options={'ordering': ['position_name', 'harmful_factor'], 'verbose_name': '📋 Вредный фактор профессии', 'verbose_name_plural': '📋 Вредные факторы по профессиям'},
        ),
        migrations.AlterModelOptions(
            name='medicalexaminationtype',
            options={'ordering': ['name'], 'verbose_name': '🩺 Вид медицинского осмотра', 'verbose_name_plural': '🩺 Виды медицинских осмотров'},
        ),
        migrations.AlterModelOptions(
            name='medicalreferral',
            options={'ordering': ['-issue_date', '-created_at'], 'verbose_name': '📋 Направление на медосмотр', 'verbose_name_plural': '📋 Направления на медосмотры'},
        ),
        migrations.AlterModelOptions(
            name='medicalsettings',
            options={'ordering': ['organization__short_name_ru'], 'verbose_name': '⚙️ Настройки медосмотров', 'verbose_name_plural': '⚙️ Настройки медосмотров'},
        ),
        migrations.AlterModelOptions(
            name='organizationkeydeadline',
            options={'verbose_name': '📅 Организация', 'verbose_name_plural': '📅 Ключевые сроки'},
        ),
        migrations.AlterModelOptions(
            name='positionmedicalfactor',
            options={'ordering': ['position', 'harmful_factor'], 'verbose_name': '🔗 Вредный фактор должности', 'verbose_name_plural': '🔗 Вредные факторы должностей'},
        ),
        migrations.AlterField(
            model_name='emailtemplatetype',
            name='available_variables',
            field=models.JSONField(blank=True, default=dict, help_text='JSON с доступными переменными и их описанием', verbose_name='Доступные переменные'),
        ),
        migrations.AlterField(
            model_name='equipmentjournalsenddetail',
            name='status',
            field=models.CharField(choices=[('success', '✅ Отправлено'), ('failed', '❌ Ошибка'), ('skipped', '⏭️ Пропущено')], max_length=20, verbose_name='Статус'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='DocumentEmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_types', models.JSONField(default=list, help_text='Список типов отправленных документов', verbose_name='Типы документов')),
                ('recipients', models.JSONField(default=list, help_text='Список email адресов получателей', verbose_name='Получатели')),
                ('recipients_count', models.IntegerField(default=0, verbose_name='Количество получателей')),
                ('documents_count', models.IntegerField(default=0, help_text='Количество документов во вложениях', verbose_name='Количество документов')),
                ('status', models.CharField(choices=[('success', '✅ Отправлено успешно'), ('failed', '❌ Ошибка отправки')], default='success', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, default='', help_text='Текст ошибки, если отправка не удалась', verbose_name='Сообщение об ошибке')),
                ('email_subject', models.CharField(blank=True, default='', max_length=500, verbose_name='Тема письма')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('employee', models.ForeignKey(help_text='Сотрудник, для которого отправлялись документы', on_delete=django.db.models.deletion.CASCADE, related_name='document_email_send_logs', to='directory.employee', verbose_name='Сотрудник')),
                ('hiring', models.ForeignKey(blank=True, help_text='Связанная запись о приеме на работу (если отправка из hiring)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_email_send_logs', to='directory.employeehiring', verbose_name='Запись о приеме')),
                ('sent_by', models.ForeignKey(blank=True, help_text='Пользователь, который инициировал отправку', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отправил')),
            ],
            options={
                'verbose_name': '📧 Документы приема',
                'verbose_name_plural': '📧 Документы приема',
                'db_table': 'directory_documentemailsendlog',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['employee', '-sent_at'], name='directory_d_employe_7a66bf_idx'), models.Index(fields=['hiring', '-sent_at'], name='directory_d_hiring__a206db_idx'), models.Index(fields=['status'], name='directory_d_status_b701b2_idx'), models.Index(fields=['-sent_at'], name='directory_d_sent_at_b40f5a_idx')],
            },
                ),
            ],
            database_operations=[
                # Таблица уже существует в БД как directory_documentemailsendlog,
                # поэтому не нужно выполнять никаких операций с базой данных
            ],
        ),
    ]
