# Generated by Django 5.0.14 on 2026-01-04 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0033_add_document_email_send_log_from_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='connection_timeout',
            field=models.PositiveSmallIntegerField(default=30, help_text='Максимальное время ожидания ответа от SMTP сервера. Рекомендуется 30 секунд.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)], verbose_name='Таймаут соединения (сек)'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='email_delay_seconds',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Пауза между отправкой писем при массовой рассылке. Защита от блокировки SMTP провайдером. Gmail/Yandex: рекомендуется 1-2 сек.', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(60.0)], verbose_name='Задержка между письмами (сек)'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='max_retry_attempts',
            field=models.PositiveSmallIntegerField(default=3, help_text='Количество попыток повторной отправки при временных ошибках. 0 = без повторов, рекомендуется 3.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Макс. попыток повтора'),
        ),
    ]
