# Generated by Django 5.0.14 on 2026-01-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0035_add_department_to_send_detail'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='instructionjournalsenddetail',
            new_name='deadline_co_send_lo_922a23_idx',
            old_name='deadli_deadli_send_lo_e9f079_idx',
        ),
        migrations.RenameIndex(
            model_name='instructionjournalsenddetail',
            new_name='deadline_co_subdivi_02c90d_idx',
            old_name='deadli_deadli_subdivi_3cc136_idx',
        ),
        migrations.RenameIndex(
            model_name='instructionjournalsenddetail',
            new_name='deadline_co_departm_f06b5e_idx',
            old_name='deadli_deadli_departm_9e34ab_idx',
        ),
        migrations.AlterField(
            model_name='harmfulfactor',
            name='full_name',
            field=models.CharField(help_text='Полное наименование вредного производственного фактора (до 1000 символов)', max_length=1000, verbose_name='Полное наименование'),
        ),
    ]
