# Generated by Django 5.0.14 on 2026-03-10 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0036_extend_harmfulfactor_full_name'),
        ('directory', '0077_add_siz_mass_generation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SIZCardSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('total_subdivisions', models.IntegerField(default=0, verbose_name='Всего подразделений')),
                ('successful_count', models.IntegerField(default=0, verbose_name='Успешных отправок')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Ошибок отправки')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='Пропущено')),
                ('total_cards', models.IntegerField(default=0, verbose_name='Всего карточек')),
                ('test_mode', models.BooleanField(default=False, verbose_name='Тестовый режим')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершено успешно'), ('partial', 'Завершено частично'), ('failed', 'Ошибка')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запуска')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_siz_card_sends', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siz_card_send_logs', to='directory.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': '🛡️ Карточки СИЗ',
                'verbose_name_plural': '🛡️ Карточки СИЗ',
                'ordering': ['-created_at'],
            },
        ),
    ]
