# Generated by Django 5.0.14 on 2026-04-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0037_add_siz_card_send_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizcardsendlog',
            options={'ordering': ['-created_at'], 'verbose_name': '🛡️ Журнал отправки карточек СИЗ', 'verbose_name_plural': '🛡️ Журнал отправки карточек СИЗ'},
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='test_email',
            field=models.EmailField(blank=True, default='', help_text='Адрес, на который уходят все письма в тестовом режиме', max_length=254, verbose_name='Email для тестовых рассылок'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='test_mode',
            field=models.BooleanField(default=False, help_text='Все письма будут отправляться только на тестовый адрес, а не реальным получателям', verbose_name='Тестовый режим'),
        ),
    ]
