# Generated by Django 5.0.14 on 2026-01-07 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0065_fix_commission_type_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, unique=True, verbose_name='Образование (рус)')),
                ('name_by', models.CharField(blank=True, max_length=255, verbose_name='Образование (бел)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': '🎓 Уровень образования',
                'verbose_name_plural': '🎓 Уровни образования',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Код типа обучения (например: preparation, retraining)', max_length=50, unique=True, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус)')),
                ('name_by', models.CharField(blank=True, max_length=255, verbose_name='Название (бел)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': '🎓 Тип обучения',
                'verbose_name_plural': '🎓 Типы обучения',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru_nominative', models.CharField(max_length=255, verbose_name='Профессия (рус, им.)')),
                ('name_ru_genitive', models.CharField(max_length=255, verbose_name='Профессия (рус, род.)')),
                ('name_by_nominative', models.CharField(blank=True, max_length=255, verbose_name='Профессия (бел, им.)')),
                ('name_by_genitive', models.CharField(blank=True, max_length=255, verbose_name='Профессия (бел, род.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': '🧑\u200d🏭 Профессия обучения',
                'verbose_name_plural': '🧑\u200d🏭 Профессии обучения',
                'ordering': ['order', 'name_ru_nominative'],
                'unique_together': {('name_ru_nominative', 'name_ru_genitive')},
            },
        ),
        migrations.CreateModel(
            name='TrainingQualificationGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_number', models.PositiveIntegerField(verbose_name='Номер разряда')),
                ('label_ru', models.CharField(help_text='Например: 3 (третий)', max_length=255, verbose_name='Разряд (рус)')),
                ('label_by', models.CharField(blank=True, max_length=255, verbose_name='Разряд (бел)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': '🧩 Разряд квалификации',
                'verbose_name_plural': '🧩 Разряды квалификации',
                'ordering': ['order', 'grade_number'],
                'unique_together': {('grade_number', 'label_ru')},
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название программы')),
                ('content', models.JSONField(blank=True, default=dict, help_text='JSON с разделами, темами и часами', verbose_name='Содержание программы')),
                ('duration_days', models.PositiveIntegerField(default=0, verbose_name='Длительность (дни)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='production_training.trainingprofession', verbose_name='Профессия')),
                ('qualification_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='production_training.trainingqualificationgrade', verbose_name='Разряд')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='production_training.trainingtype', verbose_name='Тип обучения')),
            ],
            options={
                'verbose_name': '📘 Программа обучения',
                'verbose_name_plural': '📘 Программы обучения',
                'ordering': ['training_type', 'profession', 'name'],
                'unique_together': {('name', 'training_type', 'profession')},
            },
        ),
        migrations.CreateModel(
            name='ProductionTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prior_qualification', models.TextField(blank=True, help_text='Например: автослесарь, А№0584083 от 09.02.2009', verbose_name='Имеющаяся квалификация')),
                ('workplace', models.CharField(blank=True, help_text='Например: склад, цех №1', max_length=255, verbose_name='Место работы')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала обучения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания обучения')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='Дата экзамена')),
                ('exam_score', models.CharField(blank=True, max_length=50, verbose_name='Отметка за экзамен')),
                ('practical_date', models.DateField(blank=True, null=True, verbose_name='Дата пробной работы')),
                ('practical_score', models.CharField(blank=True, max_length=50, verbose_name='Отметка за пробную работу')),
                ('practical_work_topic', models.TextField(blank=True, verbose_name='Тема пробной работы')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='Регистрационный номер')),
                ('protocol_number', models.CharField(blank=True, max_length=100, verbose_name='Номер протокола')),
                ('protocol_date', models.DateField(blank=True, null=True, verbose_name='Дата протокола')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи удостоверения')),
                ('training_city_ru', models.CharField(blank=True, max_length=255, verbose_name='Место проведения (рус)')),
                ('training_city_by', models.CharField(blank=True, max_length=255, verbose_name='Место проведения (бел)')),
                ('planned_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='План часов')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Факт часов')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'В процессе'), ('completed', 'Завершено')], default='draft', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('commission_chairman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_as_chairman', to='directory.employee', verbose_name='Председатель квалификационной комиссии')),
                ('commission_members', models.ManyToManyField(blank=True, related_name='training_as_member', to='directory.employee', verbose_name='Члены комиссии')),
                ('current_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_trainings', to='directory.position', verbose_name='Профессия на предприятии')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_trainings', to='directory.department', verbose_name='Отдел')),
                ('education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='production_training.educationlevel', verbose_name='Образование')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_trainings', to='directory.employee', verbose_name='Сотрудник')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_as_instructor', to='directory.employee', verbose_name='Инструктор производственного обучения')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_trainings', to='directory.organization', verbose_name='Организация')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_trainings', to='directory.structuralsubdivision', verbose_name='Подразделение')),
                ('theory_consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_as_consultant', to='directory.employee', verbose_name='Консультант по теории')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='production_training.trainingprofession', verbose_name='Профессия обучения')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='production_training.trainingprogram', verbose_name='Программа')),
                ('qualification_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='production_training.trainingqualificationgrade', verbose_name='Разряд')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='production_training.trainingtype', verbose_name='Тип обучения')),
            ],
            options={
                'verbose_name': '📒 Обучение на производстве',
                'verbose_name_plural': '📒 Обучение на производстве',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'employee'], name='pt_org_emp_idx'), models.Index(fields=['start_date', 'end_date'], name='pt_dates_idx'), models.Index(fields=['status'], name='pt_status_idx')],
            },
        ),
    ]
