# Generated by Django 5.0.14 on 2026-01-17 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0069_add_default_training_roles_to_organization'),
        ('production_training', '0006_make_employee_optional_and_add_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='consultation_hours',
            field=models.PositiveIntegerField(default=0, help_text='Часы на консультации', verbose_name='Консультации'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='exam_hours',
            field=models.PositiveIntegerField(default=8, help_text='Часы на квалификационный экзамен', verbose_name='Экзамен'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='practice_hours',
            field=models.PositiveIntegerField(default=0, help_text='Производственное обучение, практика', verbose_name='Лабораторно-практические'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='theory_hours',
            field=models.PositiveIntegerField(default=0, help_text='Технология, техника, охрана труда и др.', verbose_name='Теория (лекции)'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='total_hours',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество часов программы', verbose_name='Всего часов'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='weeks_count',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество недель обучения', verbose_name='Количество недель'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='weeks_distribution',
            field=models.JSONField(blank=True, default=list, help_text='Распределение часов: [40, 40, 40, 40, 32]', verbose_name='Часы по неделям'),
        ),
        migrations.AlterField(
            model_name='productiontraining',
            name='commission_chairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_as_chairman', to='directory.employee', verbose_name='Руководитель производственного обучения'),
        ),
        migrations.AlterField(
            model_name='productiontraining',
            name='theory_consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_as_consultant', to='directory.employee', verbose_name='Консультант теоретического обучения'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Устаревшее поле. Используйте простые поля выше.', verbose_name='Содержание (deprecated)'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='duration_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность (deprecated)'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='weekly_hours',
            field=models.JSONField(blank=True, default=list, help_text='Устаревшее. Используйте weeks_distribution.', verbose_name='Недельные часы (deprecated)'),
        ),
    ]
