# Generated by Django 5.0.14 on 2026-01-17 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_training', '0007_add_simple_hours_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogram',
            name='consultation_hours',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='exam_hours',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='practice_hours',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='theory_hours',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='weeks_count',
        ),
    ]
