# Generated by Django 5.0.14 on 2026-01-18 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0073_merge_20260118_1253'),
        ('production_training', '0009_remove_education_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prior_qualification', models.TextField(blank=True, help_text='Например: автослесарь, А№0584083 от 09.02.2009', verbose_name='Имеющаяся квалификация')),
                ('workplace', models.CharField(blank=True, help_text='Например: склад, цех №1', max_length=255, verbose_name='Место работы')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала обучения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания обучения')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='Дата экзамена')),
                ('exam_score', models.CharField(blank=True, max_length=50, verbose_name='Отметка за экзамен')),
                ('practical_date', models.DateField(blank=True, null=True, verbose_name='Дата пробной работы')),
                ('practical_score', models.CharField(blank=True, max_length=50, verbose_name='Отметка за пробную работу')),
                ('practical_work_topic', models.TextField(blank=True, verbose_name='Тема пробной работы')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='Регистрационный номер')),
                ('protocol_number', models.CharField(blank=True, max_length=100, verbose_name='Номер протокола')),
                ('protocol_date', models.DateField(blank=True, null=True, verbose_name='Дата протокола')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи удостоверения')),
                ('planned_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='План часов')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Факт часов')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('current_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_assignments', to='directory.position', verbose_name='Профессия на предприятии')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_assignments', to='directory.employee', verbose_name='Сотрудник')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='production_training.productiontraining', verbose_name='Курс обучения')),
            ],
            options={
                'verbose_name': '👤 Сотрудник на обучении',
                'verbose_name_plural': '👥 Сотрудники на обучении',
                'ordering': ['-start_date', 'employee__full_name_nominative'],
                'indexes': [models.Index(fields=['training', 'employee'], name='ta_training_emp_idx'), models.Index(fields=['start_date', 'end_date'], name='ta_dates_idx')],
                'unique_together': {('training', 'employee')},
            },
        ),
    ]
