# Generated by Django 5.0.14 on 2026-01-18 10:43

from django.db import migrations, models


def forwards_copy_assignments(apps, schema_editor):
    Training = apps.get_model('production_training', 'ProductionTraining')
    Assignment = apps.get_model('production_training', 'TrainingAssignment')
    db_alias = schema_editor.connection.alias

    for training in Training.objects.using(db_alias).all().iterator():
        if not training.employee_id:
            continue
        Assignment.objects.using(db_alias).get_or_create(
            training_id=training.id,
            employee_id=training.employee_id,
            defaults={
                'current_position_id': training.current_position_id,
                'prior_qualification': training.prior_qualification or '',
                'workplace': training.workplace or '',
                'start_date': training.start_date,
                'end_date': training.end_date,
                'exam_date': training.exam_date,
                'exam_score': training.exam_score or '',
                'practical_date': training.practical_date,
                'practical_score': training.practical_score or '',
                'practical_work_topic': training.practical_work_topic or '',
                'registration_number': training.registration_number or '',
                'protocol_number': training.protocol_number or '',
                'protocol_date': training.protocol_date,
                'issue_date': training.issue_date,
                'planned_hours': training.planned_hours,
                'actual_hours': training.actual_hours,
                'notes': training.notes or '',
            },
        )


def backwards_copy_assignments(apps, schema_editor):
    # Данные остаются в TrainingAssignment (обратный перенос не требуется).
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0073_merge_20260118_1253'),
        ('production_training', '0010_add_training_assignment'),
    ]

    operations = [
        migrations.RunPython(forwards_copy_assignments, backwards_copy_assignments),
        migrations.AlterModelOptions(
            name='productiontraining',
            options={'ordering': ['-created_at'], 'verbose_name': '📘 Курс обучения', 'verbose_name_plural': '📘 Курсы обучения'},
        ),
        migrations.RemoveIndex(
            model_name='productiontraining',
            name='pt_org_emp_idx',
        ),
        migrations.RemoveIndex(
            model_name='productiontraining',
            name='pt_dates_idx',
        ),
        migrations.RemoveIndex(
            model_name='productiontraining',
            name='pt_status_idx',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='actual_hours',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='current_position',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='exam_score',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='planned_hours',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='practical_date',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='practical_score',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='practical_work_topic',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='prior_qualification',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='protocol_date',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='protocol_number',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='status',
        ),
        migrations.RemoveField(
            model_name='productiontraining',
            name='workplace',
        ),
        migrations.AddIndex(
            model_name='productiontraining',
            index=models.Index(fields=['organization'], name='pt_org_idx'),
        ),
    ]
