# Generated by Django 5.0.14 on 2026-01-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0073_merge_20260118_1253'),
        ('production_training', '0011_split_to_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontraining',
            name='responsible_person',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='training_as_responsible',
                to='directory.employee',
                verbose_name='Ответственный за обучение',
            ),
        ),
    ]
