# Generated by Django 5.0.12 on 2025-04-21 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0018_alter_employee_is_contractor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiring_date', models.DateField(help_text='Дата приема на работу', verbose_name='Дата приема')),
                ('start_date', models.DateField(help_text='Дата фактического начала работы', verbose_name='Дата начала работы')),
                ('hiring_type', models.CharField(choices=[('new', '🆕 Новый сотрудник'), ('transfer', '↔️ Перевод'), ('return', '↩️ Возврат из отпуска'), ('contractor', '📄 Договор подряда'), ('part_time', '🔄 Совместительство')], default='new', max_length=20, verbose_name='Вид приема')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hirings', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hirings', to='directory.department', verbose_name='Отдел')),
                ('documents', models.ManyToManyField(blank=True, related_name='hiring_records', to='directory.generateddocument', verbose_name='Сгенерированные документы')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hirings', to='directory.employee', verbose_name='Сотрудник')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hirings', to='directory.organization', verbose_name='Организация')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hirings', to='directory.position', verbose_name='Должность')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hirings', to='directory.structuralsubdivision', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Прием на работу',
                'verbose_name_plural': 'Приемы на работу',
                'ordering': ['-hiring_date', 'employee__full_name_nominative'],
            },
        ),
    ]
