# Generated by Django 5.0.14 on 2025-11-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0036_add_quiz_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siz',
            name='classification',
            field=models.CharField(blank=True, default='', help_text='Маркировка СИЗ по защитным свойствам или конструктивным особенностям', max_length=100, verbose_name='Классификация (маркировка)'),
        ),
    ]
