# Generated by Django 5.0.14 on 2025-11-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0037_siz_classification_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='siz',
            name='wear_type',
            field=models.CharField(blank=True, default='', help_text="Для wear_period=0: 'До износа', 'Дежурный', 'Дежурная', 'Дежурные'", max_length=50, verbose_name='Тип выдачи'),
        ),
        migrations.AlterField(
            model_name='siz',
            name='wear_period',
            field=models.PositiveIntegerField(default=12, help_text='0 означает особые случаи (До износа, Дежурные и т.д.)', verbose_name='Срок носки в месяцах'),
        ),
    ]
