# Generated by Django 5.0.14 on 2025-11-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0002_migrate_equipment_data'),
        ('directory', '0038_add_siz_wear_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='positions', to='deadline_control.equipment', verbose_name='Оборудование'),
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
