# Generated by Django 5.0.14 on 2025-11-16 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0040_remove_old_medical_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_types', models.JSONField(default=list, help_text='Список типов сгенерированных документов', verbose_name='Типы документов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_generation_logs', to='directory.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Лог генерации документов',
                'verbose_name_plural': 'Логи генерации документов',
                'ordering': ['-created_at'],
            },
        ),
    ]
