# Generated by Django 5.0.14 on 2025-11-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0041_add_document_generation_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='📂 Доступ только к конкретным отделам', related_name='user_profiles', to='directory.department', verbose_name='Отделы'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subdivisions',
            field=models.ManyToManyField(blank=True, help_text='🏭 Доступ к подразделениям (включая их отделы)', related_name='user_profiles', to='directory.structuralsubdivision', verbose_name='Структурные подразделения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='🏢 Доступ ко ВСЕЙ организации (все подразделения и отделы)', related_name='user_profiles', to='directory.organization', verbose_name='Организации'),
        ),
    ]
