# Generated by Django 5.0.14 on 2025-11-21 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0042_add_subdivisions_departments_to_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название пункта меню, отображаемое пользователю', max_length=100, verbose_name='Название')),
                ('icon', models.CharField(blank=True, help_text='Emoji или CSS класс иконки (например: 👥, 🔧)', max_length=50, verbose_name='Иконка')),
                ('url_name', models.CharField(blank=True, help_text='Django URL name (например: directory:employees:list) или внешний URL', max_length=200, verbose_name='URL name')),
                ('url', models.CharField(blank=True, help_text='Прямой URL (если url_name не указан)', max_length=500, verbose_name='Прямой URL')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения (меньше = выше)', verbose_name='Порядок')),
                ('location', models.CharField(choices=[('sidebar', 'Боковое меню'), ('top', 'Верхнее меню'), ('both', 'Оба меню')], default='sidebar', help_text='Где отображается этот пункт меню', max_length=20, verbose_name='Расположение')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные пункты не отображаются никому', verbose_name='Активен')),
                ('requires_auth', models.BooleanField(default=True, help_text='Показывать только авторизованным пользователям', verbose_name='Требует авторизации')),
                ('is_separator', models.BooleanField(default=False, help_text='Визуальный разделитель между группами пунктов', verbose_name='Разделитель')),
                ('description', models.TextField(blank=True, help_text='Описание для администраторов', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, help_text='Для создания вложенных меню', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='directory.menuitem', verbose_name='Родительский пункт')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='visible_menu_items',
            field=models.ManyToManyField(blank=True, help_text='🍔 Пункты меню, доступные пользователю. Если не указаны - доступны все.', related_name='user_profiles', to='directory.menuitem', verbose_name='Доступные пункты меню'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['parent', 'order'], name='directory_m_parent__861de1_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['location', 'is_active'], name='directory_m_locatio_950a92_idx'),
        ),
    ]
