# Generated by Django 5.0.14 on 2025-11-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0043_add_menu_item_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='commission_role',
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='document_type',
            field=models.CharField(choices=[('all_orders', '📝 Распоряжения о стажировке'), ('knowledge_protocol', '📋 Протокол проверки знаний по охране труда'), ('periodic_protocol', '📋 Протокол периодической проверки знаний'), ('doc_familiarization', '📝 Лист ознакомления с документами'), ('siz_card', '🛡️ Карточка учета СИЗ'), ('personal_ot_card', '👤 Личная карточка по ОТ'), ('journal_example', '📒 Образец заполнения журнала')], max_length=50, verbose_name='Тип документа'),
        ),
    ]
