# Generated by Django 5.2.6 on 2025-11-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0044_remove_commission_role_from_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='company_vehicle_instructions',
            field=models.CharField(blank=True, help_text='Укажите номера инструкций по охране труда для водителей служебного транспорта', max_length=255, verbose_name='🚗 Инструкции при управлении служебным автомобилем'),
        ),
        migrations.AddField(
            model_name='position',
            name='drives_company_vehicle',
            field=models.BooleanField(default=False, help_text='Отметьте, если должность предполагает управление служебным автомобилем', verbose_name='🚗 Управляет служебным автомобилем'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='document_type',
            field=models.CharField(choices=[('journal_example', '📒 Образец заполнения журнала'), ('all_orders', '📝 Распоряжения о стажировке'), ('knowledge_protocol', '📋 Протокол проверки знаний по охране труда'), ('periodic_protocol', '📋 Протокол периодической проверки знаний'), ('doc_familiarization', '📝 Лист ознакомления с документами'), ('siz_card', '🛡️ Карточка учета СИЗ'), ('personal_ot_card', '👤 Личная карточка по ОТ')], max_length=50, verbose_name='Тип документа'),
        ),
    ]
