# Generated by Django 5.0.14 on 2025-11-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0045_add_company_vehicle_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название вида ответственности')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о виде ответственности', verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, help_text='Используется для упорядочивания в списках', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные виды ответственности не отображаются в формах', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вид ответственного',
                'verbose_name_plural': 'Виды ответственных',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='position',
            name='responsibility_types',
            field=models.ManyToManyField(blank=True, help_text='Выберите виды ответственности для данной должности', related_name='positions', to='directory.responsibilitytype', verbose_name='📋 Виды ответственности'),
        ),
    ]
