# Generated by Django 5.0.14 on 2025-12-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0046_add_responsibility_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='document_type',
            field=models.CharField(choices=[('journal_example', '📒 Образец заполнения журнала'), ('instruction_journal', '📝 Образец журнала повторных инструктажей'), ('all_orders', '📝 Распоряжения о стажировке'), ('knowledge_protocol', '📋 Протокол проверки знаний по охране труда'), ('periodic_protocol', '📋 Протокол периодической проверки знаний'), ('doc_familiarization', '📝 Лист ознакомления с документами'), ('siz_card', '🛡️ Карточка учета СИЗ'), ('personal_ot_card', '👤 Личная карточка по ОТ')], max_length=50, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Дата приема на работу. Может быть пустой при импорте и заполнена позже', null=True, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, help_text='Дата фактического начала работы. Может быть пустой при импорте и заполнена позже', null=True, verbose_name='Дата начала работы'),
        ),
    ]
