# Generated by Django 5.0.14 on 2025-12-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0047_make_hire_date_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Дата рождения сотрудника. Может быть пустой при импорте и заполнена позже', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='place_of_residence',
            field=models.TextField(blank=True, default='', help_text='Адрес места проживания. Может быть пустым при импорте и заполнен позже', verbose_name='Место проживания'),
        ),
    ]
