# Generated by Django 5.0.14 on 2025-12-04 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0048_make_employee_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email сотрудника для получения уведомлений (особенно важно для ответственных за охрану труда)', max_length=254, verbose_name='Email'),
        ),
        migrations.CreateModel(
            name='SubdivisionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email-адрес получателя уведомлений (например: engineer@company.com)', max_length=254, verbose_name='Email для уведомлений')),
                ('description', models.CharField(blank=True, default='', help_text='Роль получателя: "Главный инженер", "Мастер участка", "Служба ОТ" и т.д.', max_length=255, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Если отключено, уведомления на этот адрес отправляться не будут', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('subdivision', models.ForeignKey(help_text='Подразделение, для которого настраивается email', on_delete=django.db.models.deletion.CASCADE, related_name='notification_emails', to='directory.structuralsubdivision', verbose_name='Структурное подразделение')),
            ],
            options={
                'verbose_name': 'Email для уведомлений',
                'verbose_name_plural': 'Email для уведомлений',
                'ordering': ['subdivision__name', 'email'],
                'indexes': [models.Index(fields=['subdivision', 'is_active'], name='directory_s_subdivi_75a10a_idx')],
                'unique_together': {('subdivision', 'email')},
            },
        ),
    ]
