# Generated by Django 5.0.14 on 2025-12-20 10:15

from django.db import migrations


def update_menu_items(apps, schema_editor):
    MenuItem = apps.get_model("directory", "MenuItem")

    separator = MenuItem.objects.filter(
        name="Контроль сроков",
        location="sidebar",
    ).order_by("id").first()
    if separator:
        separator_updates = []
        if not separator.icon:
            separator.icon = "⏱️"
            separator_updates.append("icon")
        if not separator.is_separator:
            separator.is_separator = True
            separator_updates.append("is_separator")
        if separator_updates:
            separator.save(update_fields=separator_updates)

    def set_item_fields(item, updates):
        if updates:
            item.save(update_fields=updates)

    def apply_defaults(item, defaults):
        updates = []
        for key, value in defaults.items():
            current = getattr(item, key)
            if current != value:
                setattr(item, key, value)
                updates.append(key)
        return updates

    dashboard_item = MenuItem.objects.filter(
        name="Dashboard",
        location="sidebar",
    ).order_by("id").first()
    if dashboard_item:
        updates = []
        if not dashboard_item.icon:
            dashboard_item.icon = "📊"
            updates.append("icon")
        updates += apply_defaults(
            dashboard_item,
            {"order": 21, "parent": separator} if separator else {"order": 21},
        )
        set_item_fields(dashboard_item, updates)

    equipment_item = MenuItem.objects.filter(
        name="ТО оборудования",
        location="sidebar",
    ).order_by("id").first()
    if equipment_item:
        updates = []
        if not equipment_item.icon:
            equipment_item.icon = "⚙️"
            updates.append("icon")
        updates += apply_defaults(
            equipment_item,
            {"order": 22, "parent": separator} if separator else {"order": 22},
        )
        set_item_fields(equipment_item, updates)

    equipment_types_item, created = MenuItem.objects.get_or_create(
        name="Типы оборудования",
        defaults={
            "url_name": "admin:deadline_control_equipmenttype_changelist",
            "location": "sidebar",
            "icon": "🧰",
            "order": 23,
            "is_active": True,
            "requires_auth": True,
            "parent": separator,
        },
    )
    if not created:
        updates = []
        if not equipment_types_item.icon:
            equipment_types_item.icon = "🧰"
            updates.append("icon")
        updates += apply_defaults(
            equipment_types_item,
            {
                "url_name": equipment_types_item.url_name
                or "admin:deadline_control_equipmenttype_changelist",
                "location": "sidebar",
                "order": 23,
                "parent": separator,
            },
        )
        set_item_fields(equipment_types_item, updates)

    deadlines_item = MenuItem.objects.filter(
        name="Ключевые сроки",
        location="sidebar",
    ).order_by("id").first()
    if deadlines_item:
        updates = []
        if not deadlines_item.icon:
            deadlines_item.icon = "📅"
            updates.append("icon")
        updates += apply_defaults(
            deadlines_item,
            {"order": 24, "parent": separator} if separator else {"order": 24},
        )
        set_item_fields(deadlines_item, updates)

    medical_item = MenuItem.objects.filter(
        name="Медосмотры",
        location="sidebar",
    ).order_by("id").first()
    if medical_item:
        updates = []
        if not medical_item.icon:
            medical_item.icon = "🏥"
            updates.append("icon")
        updates += apply_defaults(
            medical_item,
            {"order": 25, "parent": separator} if separator else {"order": 25},
        )
        set_item_fields(medical_item, updates)

    for item in MenuItem.objects.filter(icon=""):
        item.icon = "🔹"
        item.save(update_fields=["icon"])


def reverse_menu_item_update(apps, schema_editor):
    MenuItem = apps.get_model("directory", "MenuItem")
    MenuItem.objects.filter(name="Типы оборудования").delete()
    MenuItem.objects.filter(icon="🔹").update(icon="")


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0051_add_equipment_type"),
    ]

    operations = [
        migrations.RunPython(update_menu_items, reverse_menu_item_update),
    ]
