# Generated by Django 5.0.14 on 2025-12-20 11:05

from django.db import migrations, models


def create_document_template_types(apps, schema_editor):
    DocumentTemplateType = apps.get_model('directory', 'DocumentTemplateType')

    # Типы документов из хардкода
    DOCUMENT_TYPES = (
        ('journal_example', '📒 Образец заполнения журнала'),
        ('instruction_journal', '📝 Образец журнала повторных инструктажей'),
        ('all_orders', '📝 Распоряжения о стажировке'),
        ('knowledge_protocol', '📋 Протокол проверки знаний по охране труда'),
        ('periodic_protocol', '📋 Протокол периодической проверки знаний'),
        ('doc_familiarization', '📝 Лист ознакомления с документами'),
        ('siz_card', '🛡️ Карточка учета СИЗ'),
        ('personal_ot_card', '👤 Личная карточка по ОТ'),
    )

    for code, name in DOCUMENT_TYPES:
        DocumentTemplateType.objects.get_or_create(
            code=code,
            defaults={
                'name': name,
                'is_active': True,
            }
        )


def reverse_document_template_types(apps, schema_editor):
    DocumentTemplateType = apps.get_model('directory', 'DocumentTemplateType')
    DocumentTemplateType.objects.filter(code__in=[
        'journal_example',
        'instruction_journal',
        'all_orders',
        'knowledge_protocol',
        'periodic_protocol',
        'doc_familiarization',
        'siz_card',
        'personal_ot_card',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0052_update_menu_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Например: '🛡️ Карточка учета СИЗ'", max_length=100, unique=True, verbose_name='Название вида')),
                ('code', models.CharField(help_text="Код для использования в коде (например: 'siz_card')", max_length=50, unique=True, verbose_name='Код вида')),
                ('description', models.TextField(blank=True, help_text='Описание назначения данного вида шаблона', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '📄 Вид шаблона документа',
                'verbose_name_plural': '📄 Виды шаблонов документов',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='document_type',
            field=models.CharField(max_length=50, verbose_name='Тип документа'),
        ),
        migrations.RunPython(create_document_template_types, reverse_document_template_types),
    ]
