# Generated by Django 5.0.14 on 2025-12-23 08:17

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


def migrate_document_type_to_fk(apps, schema_editor):
    """
    Переносим данные из CharField document_type_old в ForeignKey document_type_new
    """
    DocumentTemplate = apps.get_model('directory', 'DocumentTemplate')
    DocumentTemplateType = apps.get_model('directory', 'DocumentTemplateType')

    for template in DocumentTemplate.objects.all():
        # Ищем соответствующий тип по коду
        old_code = template.document_type_old
        if old_code:
            try:
                template_type = DocumentTemplateType.objects.get(code=old_code)
                template.document_type_new = template_type
                template.save(update_fields=['document_type_new'])
            except DocumentTemplateType.DoesNotExist:
                print(f'WARNING: DocumentTemplateType with code "{old_code}" not found for template "{template.name}"')


def reverse_migrate_document_type(apps, schema_editor):
    """
    Обратная миграция: копируем код обратно в CharField
    """
    DocumentTemplate = apps.get_model('directory', 'DocumentTemplate')

    for template in DocumentTemplate.objects.all():
        if template.document_type_new:
            template.document_type_old = template.document_type_new.code
            template.save(update_fields=['document_type_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0053_add_document_template_type'),
    ]

    operations = [
        # ШАГ 1: Удаляем constraint перед переименованием поля
        migrations.RemoveConstraint(
            model_name='documenttemplate',
            name='unique_default_template_per_type',
        ),

        # ШАГ 2: Переименовываем старое поле
        migrations.RenameField(
            model_name='documenttemplate',
            old_name='document_type',
            new_name='document_type_old',
        ),

        # ШАГ 2: Создаем новое поле как ForeignKey (nullable)
        migrations.AddField(
            model_name='documenttemplate',
            name='document_type_new',
            field=models.ForeignKey(
                null=True,
                blank=True,
                help_text='Выберите тип документа из справочника',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='templates_new',
                to='directory.documenttemplatetype',
                verbose_name='Тип документа (новое)'
            ),
        ),

        # ШАГ 3: Переносим данные
        migrations.RunPython(migrate_document_type_to_fk, reverse_migrate_document_type),

        # ШАГ 4: Удаляем старое поле
        migrations.RemoveField(
            model_name='documenttemplate',
            name='document_type_old',
        ),

        # ШАГ 5: Переименовываем новое поле в document_type
        migrations.RenameField(
            model_name='documenttemplate',
            old_name='document_type_new',
            new_name='document_type',
        ),

        # ШАГ 6: Делаем поле обязательным (после переноса данных)
        migrations.AlterField(
            model_name='documenttemplate',
            name='document_type',
            field=models.ForeignKey(
                help_text='Выберите тип документа из справочника',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='templates',
                to='directory.documenttemplatetype',
                verbose_name='Тип документа'
            ),
        ),
    ]
