# Generated by Django 5.0.14 on 2025-12-28 05:30

import django.contrib.auth.models
import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('directory', '0054_convert_document_type_to_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProxy',
            fields=[
            ],
            options={
                'verbose_name': '👥 Группа',
                'verbose_name_plural': '👥 Группы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'verbose_name': '👤 Пользователь',
                'verbose_name_plural': '👤 Пользователи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question', 'order', 'id'], 'verbose_name': '💬 Ответ', 'verbose_name_plural': '💬 Ответы'},
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': '👥 Комиссия по проверке знаний', 'verbose_name_plural': '👥 Комиссии по проверке знаний'},
        ),
        migrations.AlterModelOptions(
            name='commissionmember',
            options={'ordering': ['role', 'employee__full_name_nominative'], 'verbose_name': '👤 Участник комиссии', 'verbose_name_plural': '👤 Участники комиссии'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': '📂 Отдел', 'verbose_name_plural': '📂 Отделы'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': '📄 Документ для ознакомления', 'verbose_name_plural': '📄 Документы для ознакомления'},
        ),
        migrations.AlterModelOptions(
            name='documentgenerationlog',
            options={'ordering': ['-created_at'], 'verbose_name': '📋 Лог генерации документов', 'verbose_name_plural': '📋 Логи генерации документов'},
        ),
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={'ordering': ['-updated_at'], 'verbose_name': '📝 Шаблон документа', 'verbose_name_plural': '📝 Шаблоны документов'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name_nominative'], 'verbose_name': '👤 Сотрудник', 'verbose_name_plural': '👤 Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='employeehiring',
            options={'ordering': ['-hiring_date', 'employee__full_name_nominative'], 'verbose_name': '📋 Прием на работу', 'verbose_name_plural': '📋 Приемы на работу'},
        ),
        migrations.AlterModelOptions(
            name='generateddocument',
            options={'ordering': ['-created_at'], 'verbose_name': '📄 Сгенерированный документ', 'verbose_name_plural': '📄 Сгенерированные документы'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order', 'name'], 'verbose_name': '📋 Пункт меню', 'verbose_name_plural': '📋 Пункты меню'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['full_name_ru'], 'verbose_name': '🏢 Организация', 'verbose_name_plural': '🏢 Организации'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['position_name'], 'verbose_name': '💼 Профессия/должность', 'verbose_name_plural': '💼 Профессии/должности'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['category', 'order', 'id'], 'verbose_name': '❓ Вопрос', 'verbose_name_plural': '❓ Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created'], 'verbose_name': '📝 Экзамен', 'verbose_name_plural': '📝 Экзамены'},
        ),
        migrations.AlterModelOptions(
            name='quizaccesstoken',
            options={'ordering': ['-created'], 'verbose_name': '🔑 Токен доступа к экзамену', 'verbose_name_plural': '🔑 Токены доступа к экзаменам'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at'], 'verbose_name': '📊 Попытка прохождения', 'verbose_name_plural': '📊 Попытки прохождения'},
        ),
        migrations.AlterModelOptions(
            name='quizcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': '📚 Раздел', 'verbose_name_plural': '📚 Разделы'},
        ),
        migrations.AlterModelOptions(
            name='quizcategoryorder',
            options={'ordering': ['order', 'category__name'], 'verbose_name': '🔢 Раздел в экзамене', 'verbose_name_plural': '🔢 Разделы в экзамене'},
        ),
        migrations.AlterModelOptions(
            name='quizquestionorder',
            options={'ordering': ['attempt', 'order'], 'verbose_name': '🔢 Порядок вопроса', 'verbose_name_plural': '🔢 Порядок вопросов'},
        ),
        migrations.AlterModelOptions(
            name='responsibilitytype',
            options={'ordering': ['order', 'name'], 'verbose_name': '⚖️ Вид ответственного', 'verbose_name_plural': '⚖️ Виды ответственных'},
        ),
        migrations.AlterModelOptions(
            name='siz',
            options={'ordering': ['name'], 'verbose_name': '🦺 Средство индивидуальной защиты', 'verbose_name_plural': '🦺 Средства индивидуальной защиты'},
        ),
        migrations.AlterModelOptions(
            name='siznorm',
            options={'ordering': ['position', 'condition', 'order', 'siz__name'], 'verbose_name': '📏 Норма выдачи СИЗ', 'verbose_name_plural': '📏 Нормы выдачи СИЗ'},
        ),
        migrations.AlterModelOptions(
            name='structuralsubdivision',
            options={'ordering': ['name'], 'verbose_name': '🏭 Структурное подразделение', 'verbose_name_plural': '🏭 Структурные подразделения'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['answered_at'], 'verbose_name': '✍️ Ответ пользователя', 'verbose_name_plural': '✍️ Ответы пользователей'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='use_adaptive_selection',
            field=models.BooleanField(default=False, help_text='Учитывать прогресс пользователя: приоритет вопросам с ошибками, затем новым вопросам, меньше - уже правильно отвеченным', verbose_name='Адаптивный подбор вопросов'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/document_templates/', location='/home/django/webapps/potby/media/document_templates'), upload_to='', verbose_name='Файл шаблона'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='exam_total_questions',
            field=models.IntegerField(default=10, help_text='Общее количество вопросов. Они будут распределены равномерно по всем разделам экзамена.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Всего вопросов в экзамене'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions_per_category',
            field=models.IntegerField(default=5, editable=False, help_text='[УСТАРЕЛО] Сколько случайных вопросов взять из КАЖДОГО раздела для итогового экзамена', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Вопросов из каждого раздела'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('document_type',), name='unique_default_template_per_type'),
        ),
    ]
