# Generated by Django 5.0.14 on 2026-01-01 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0057_add_department_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_types', models.JSONField(default=list, help_text='Список типов отправленных документов', verbose_name='Типы документов')),
                ('recipients', models.JSONField(default=list, help_text='Список email адресов получателей', verbose_name='Получатели')),
                ('recipients_count', models.IntegerField(default=0, verbose_name='Количество получателей')),
                ('documents_count', models.IntegerField(default=0, help_text='Количество документов во вложениях', verbose_name='Количество документов')),
                ('status', models.CharField(choices=[('success', '✅ Отправлено успешно'), ('failed', '❌ Ошибка отправки')], default='success', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, default='', help_text='Текст ошибки, если отправка не удалась', verbose_name='Сообщение об ошибке')),
                ('email_subject', models.CharField(blank=True, default='', max_length=500, verbose_name='Тема письма')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': '📧 Лог отправки документов',
                'verbose_name_plural': '📧 Логи отправки документов',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='departmentemail',
            new_name='directory_d_departm_b18433_idx',
            old_name='directory_d_departm_d9af5f_idx',
        ),
        migrations.AlterField(
            model_name='departmentemail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documenttemplatetype',
            name='show_in_hiring',
            field=models.BooleanField(default=True, help_text='Определяет, отображается ли этот тип документа в списке для скачивания при приеме на работу', verbose_name='Показывать при приеме'),
        ),
        migrations.AddField(
            model_name='documentemailsendlog',
            name='employee',
            field=models.ForeignKey(help_text='Сотрудник, для которого отправлялись документы', on_delete=django.db.models.deletion.CASCADE, related_name='document_email_send_logs', to='directory.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='documentemailsendlog',
            name='hiring',
            field=models.ForeignKey(blank=True, help_text='Связанная запись о приеме на работу (если отправка из hiring)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_email_send_logs', to='directory.employeehiring', verbose_name='Запись о приеме'),
        ),
        migrations.AddField(
            model_name='documentemailsendlog',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='Пользователь, который инициировал отправку', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отправил'),
        ),
        migrations.AddIndex(
            model_name='documentemailsendlog',
            index=models.Index(fields=['employee', '-sent_at'], name='directory_d_employe_7a66bf_idx'),
        ),
        migrations.AddIndex(
            model_name='documentemailsendlog',
            index=models.Index(fields=['hiring', '-sent_at'], name='directory_d_hiring__a206db_idx'),
        ),
        migrations.AddIndex(
            model_name='documentemailsendlog',
            index=models.Index(fields=['status'], name='directory_d_status_b701b2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentemailsendlog',
            index=models.Index(fields=['-sent_at'], name='directory_d_sent_at_b40f5a_idx'),
        ),
    ]
