# Generated by Django 5.0.14 on 2026-01-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0058_add_document_email_send_log'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='DocumentEmailSendLog',
                ),
            ],
            database_operations=[
                # Таблица НЕ удаляется из БД, так как она будет использоваться
                # моделью DocumentEmailSendLog в приложении deadline_control
            ],
        ),
    ]
