# Generated by Django 5.0.14 on 2026-01-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline_control', '0033_add_document_email_send_log_from_directory'),
        ('directory', '0059_remove_document_email_send_log'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['position'], name='emp_position_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['organization', 'subdivision', 'department'], name='pos_tree_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['position_name'], name='pos_name_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['position_name', 'organization'], name='pos_name_org_idx'),
        ),
    ]
