# Generated by Django 5.0.14 on 2026-01-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0060_add_tree_view_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='medical_norms_overridden',
            field=models.BooleanField(default=False, help_text='Если включено, используются только нормы из таблицы ниже. Если нет норм - медосмотры не требуются.', verbose_name='🏥 Нормы медосмотров переопределены'),
        ),
        migrations.AddField(
            model_name='position',
            name='siz_norms_overridden',
            field=models.BooleanField(default=False, help_text='Если включено, используются только нормы из таблицы ниже. Если нет норм - СИЗ не положены.', verbose_name='🛡️ Нормы СИЗ переопределены'),
        ),
    ]
