# Generated by Django 5.0.14 on 2026-01-03 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0061_add_norms_override_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionSIZNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_name', models.CharField(db_index=True, help_text='Точное название профессии (регистронезависимо)', max_length=255, verbose_name='Название профессии')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('condition', models.CharField(blank=True, default='', help_text="Например: 'При влажной уборке помещений', 'При работе на высоте' и т.д.", max_length=255, verbose_name='Условие выдачи')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('siz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_norms', to='directory.siz', verbose_name='СИЗ')),
            ],
            options={
                'verbose_name': '📖 Эталонная норма СИЗ профессии',
                'verbose_name_plural': '📖 Эталонные нормы СИЗ профессий',
                'ordering': ['profession_name', 'condition', 'order', 'siz__name'],
                'indexes': [models.Index(fields=['profession_name'], name='prof_siz_name_idx')],
                'unique_together': {('profession_name', 'siz', 'condition')},
            },
        ),
    ]
