# Generated by Django 5.0.14 on 2026-01-03 15:50

from django.db import migrations


def migrate_siz_norms_to_profession(apps, schema_editor):
    """
    Миграция эталонных норм СИЗ из должностей в справочник профессий.

    Для каждой профессии (уникального position_name):
    1. Находит должность с нормами (первую по алфавиту организаций)
    2. Копирует её нормы в ProfessionSIZNorm
    3. Сохраняет количество, условие и порядок
    """
    Position = apps.get_model('directory', 'Position')
    SIZNorm = apps.get_model('directory', 'SIZNorm')
    ProfessionSIZNorm = apps.get_model('directory', 'ProfessionSIZNorm')

    # Получаем все уникальные названия профессий, у которых есть нормы СИЗ
    position_names = SIZNorm.objects.values_list(
        'position__position_name', flat=True
    ).distinct()

    migrated_count = 0
    skipped_count = 0

    for position_name in position_names:
        if not position_name:
            skipped_count += 1
            continue

        # Находим эталонную должность (первую по алфавиту организаций)
        reference_position = Position.objects.filter(
            position_name=position_name,
            siz_norms__isnull=False
        ).order_by('organization__full_name_ru').first()

        if not reference_position:
            skipped_count += 1
            continue

        # Получаем нормы эталонной должности
        norms = SIZNorm.objects.filter(position=reference_position).order_by('order')

        # Копируем нормы в ProfessionSIZNorm
        for norm in norms:
            # Проверяем, не существует ли уже такая норма
            existing = ProfessionSIZNorm.objects.filter(
                profession_name=position_name,
                siz=norm.siz,
                condition=norm.condition
            ).first()

            if not existing:
                ProfessionSIZNorm.objects.create(
                    profession_name=position_name,
                    siz=norm.siz,
                    quantity=norm.quantity,
                    condition=norm.condition,
                    order=norm.order
                )
                migrated_count += 1

    print(f"✅ Мигрировано {migrated_count} эталонных норм СИЗ")
    print(f"⏩  Пропущено {skipped_count} профессий без норм")


def reverse_migration(apps, schema_editor):
    """
    Откат миграции - удаляет все записи из ProfessionSIZNorm
    """
    ProfessionSIZNorm = apps.get_model('directory', 'ProfessionSIZNorm')
    count = ProfessionSIZNorm.objects.count()
    ProfessionSIZNorm.objects.all().delete()
    print(f"🔄 Удалено {count} эталонных норм при откате миграции")


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0062_add_profession_siz_norm'),
    ]

    operations = [
        migrations.RunPython(migrate_siz_norms_to_profession, reverse_migration),
    ]
