# Generated by Django 5.0.14 on 2026-01-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0063_migrate_siz_norms_to_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionmember',
            name='role',
            field=models.CharField(choices=[('chairman', '👑 Председатель комиссии'), ('vice_chairman', '🥈 Заместитель председателя комиссии'), ('member', '👤 Член комиссии'), ('secretary', '📝 Секретарь комиссии')], default='member', max_length=20, verbose_name='Роль в комиссии'),
        ),
    ]
