# Generated by Django 5.0.14 on 2026-01-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0064_add_vice_chairman_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commission_type',
            field=models.CharField(choices=[('ot', '🛡️ Охрана труда'), ('eb', '⚡ Электробезопасность'), ('pb', '🔥 Пожарная безопасность'), ('qualification', '🎓 Квалификационная комиссия'), ('other', '📋 Иная')], default='ot', max_length=20, verbose_name='Тип комиссии'),
        ),
    ]
