# Generated by Django 5.0.14 on 2026-01-12 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0068_remove_employee_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_commission_chairman',
            field=models.ForeignKey(blank=True, help_text='Будет подставляться по умолчанию при создании обучения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_default_commission_chairman', to='directory.employee', verbose_name='Эталонный руководитель производственного обучения'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_instructor',
            field=models.ForeignKey(blank=True, help_text='Будет подставляться по умолчанию при создании обучения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_default_instructor', to='directory.employee', verbose_name='Эталонный инструктор производственного обучения'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_theory_consultant',
            field=models.ForeignKey(blank=True, help_text='Будет подставляться по умолчанию при создании обучения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_default_theory_consultant', to='directory.employee', verbose_name='Эталонный консультант теоретического обучения'),
        ),
    ]
