# Generated by Django 5.0.14 on 2026-01-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0070_add_default_responsible_person_to_organization'),
        ('directory', '0072_change_employee_education_level_to_text'),
    ]

    operations = [
    ]
