# Generated by Django 5.0.14 on 2026-01-31 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0073_merge_20260118_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='default_commission_chairman',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='default_instructor',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='default_responsible_person',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='default_theory_consultant',
        ),
    ]
