# Generated by Django 5.0.14 on 2026-02-07 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0074_remove_default_training_roles_from_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehiring',
            name='hiring_type',
            field=models.CharField(choices=[('new', '🆕 Новый сотрудник'), ('transfer', '↔️ Перевод'), ('return', '↩️ Возврат из отпуска'), ('contractor', '📄 Договор подряда'), ('part_time', '💤 Совместительство')], default='new', max_length=20, verbose_name='Вид приема'),
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('global', 'Единый импорт'), ('registry', 'Реестр сотрудников'), ('quiz', 'Вопросы экзаменов')], default='global', max_length=20, verbose_name='Тип импорта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата импорта')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('rolled_back', 'Откачен'), ('partial', 'Частично откачен')], default='success', max_length=20, verbose_name='Статус')),
                ('total_created', models.PositiveIntegerField(default=0, verbose_name='Создано объектов')),
                ('total_updated', models.PositiveIntegerField(default=0, verbose_name='Обновлено объектов')),
                ('total_errors', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('created_objects', models.JSONField(blank=True, default=dict, help_text='ID созданных объектов по моделям', verbose_name='Созданные объекты')),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отката')),
                ('rollback_details', models.TextField(blank=True, help_text='Что было удалено при откате', verbose_name='Детали отката')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Выполнил')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.organization', verbose_name='Организация')),
                ('rolled_back_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_logs', to=settings.AUTH_USER_MODEL, verbose_name='Откатил')),
            ],
            options={
                'verbose_name': 'Лог импорта',
                'verbose_name_plural': 'Логи импортов',
                'ordering': ['-created_at'],
            },
        ),
    ]
