# Generated by Django 5.0.14 on 2026-03-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0075_add_import_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='height',
            field=models.CharField(blank=True, choices=[('158-164 см', '158-164 см'), ('164-170 см', '164-170 см'), ('170-176 см', '170-176 см'), ('176-182 см', '176-182 см'), ('182-188 см', '182-188 см'), ('188-194 см', '188-194 см'), ('194-200 см', '194-200 см')], max_length=15, verbose_name='Рост'),
        ),
    ]
