# Generated by Django 5.0.14 on 2026-03-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0076_add_height_choices_full'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professionsiznorm',
            options={'ordering': ['profession_name', 'condition', 'order', 'siz__name'], 'verbose_name': '📖 Эталонная норма СИЗ профессии', 'verbose_name_plural': '📖 1. Эталонные нормы СИЗ (справочник)'},
        ),
        migrations.AddField(
            model_name='position',
            name='requires_siz',
            field=models.BooleanField(default=True, help_text='Если отключено, для этой должности не будут создаваться карточки СИЗ', verbose_name='🛡️ Требуются СИЗ'),
        ),
        migrations.AddField(
            model_name='structuralsubdivision',
            name='skip_email_notifications',
            field=models.BooleanField(default=False, help_text='Если включено, рассылки по подразделению и его отделам будут пропущены', verbose_name='Пропустить email-уведомления'),
        ),
        migrations.AlterField(
            model_name='professionsiznorm',
            name='condition',
            field=models.CharField(blank=True, default='', help_text="Например: 'При влажной уборке помещений'", max_length=255, verbose_name='Условие выдачи'),
        ),
    ]
