# Generated by Django 5.0.14 on 2026-03-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0077_add_siz_mass_generation_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professionsiznorm',
            options={'ordering': ['profession_name', 'condition', 'order', 'siz__name'], 'verbose_name': '📖 Эталонная норма СИЗ', 'verbose_name_plural': '📖 Эталонные нормы СИЗ'},
        ),
        migrations.AlterModelOptions(
            name='siz',
            options={'ordering': ['name'], 'verbose_name': '🦺 Справочник СИЗ', 'verbose_name_plural': '🦺 Справочник СИЗ'},
        ),
        migrations.AlterModelOptions(
            name='sizissued',
            options={'ordering': ['-issue_date', 'employee__full_name_nominative'], 'verbose_name': '📦 Выданное СИЗ', 'verbose_name_plural': '📦 Выданные СИЗ'},
        ),
        migrations.AlterModelOptions(
            name='siznorm',
            options={'ordering': ['position', 'condition', 'order', 'siz__name'], 'verbose_name': '📏 Переопределённая норма', 'verbose_name_plural': '📏 Переопределённые нормы'},
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
    ]
