# Generated by Django 5.0.14 on 2026-04-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0078_add_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='marked_for_deletion',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Сотрудник скрыт из рабочих разделов, но сохранен в базе',
                verbose_name='Помечен на удаление',
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='marked_for_deletion_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Дата пометки на удаление',
            ),
        ),
    ]
