# Generated by Django 5.0.14 on 2026-04-18 15:03

import directory.models.generation_job
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0079_employee_soft_delete_marker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('periodic_protocol', 'Протокол периодической проверки знаний (один файл)'), ('periodic_protocol_by_sub', 'Протоколы по подразделениям (архив)'), ('periodic_certificates', 'Удостоверения по ОТ (один файл)'), ('periodic_certificates_by_sub', 'Удостоверения по ОТ по подразделениям (архив)')], max_length=64, verbose_name='Тип задачи')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('done', 'Готово'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=16)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название (для UI)')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Параметры задачи')),
                ('progress_current', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('result_file', models.FileField(blank=True, null=True, upload_to=directory.models.generation_job._job_upload_path)),
                ('result_filename', models.CharField(blank=True, max_length=512)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача генерации',
                'verbose_name_plural': 'Задачи генерации',
                'ordering': ['-created_at'],
            },
        ),
    ]
