# Generated by Django 5.0.14 on 2026-05-24 15:53

from django.db import migrations


def sync_fired_status(apps, schema_editor):
    Employee = apps.get_model('directory', 'Employee')
    Employee.objects.filter(marked_for_deletion=True).exclude(status='fired').update(status='fired')


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0080_add_generation_job'),
    ]

    operations = [
        migrations.RunPython(sync_fired_status, migrations.RunPython.noop),
    ]
