# Generated by Django 5.0.14 on 2026-06-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0081_sync_fired_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='height_group_1',
            field=models.BooleanField(default=False, verbose_name='⛰️ Группа 1 (работа на высоте)'),
        ),
        migrations.AddField(
            model_name='position',
            name='height_group_2',
            field=models.BooleanField(default=False, verbose_name='⛰️ Группа 2 (работа на высоте)'),
        ),
        migrations.AddField(
            model_name='position',
            name='height_group_3',
            field=models.BooleanField(default=False, verbose_name='⛰️ Группа 3 (работа на высоте)'),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='job_type',
            field=models.CharField(choices=[('periodic_protocol', 'Протокол периодической проверки знаний (один файл)'), ('periodic_protocol_by_sub', 'Протоколы по подразделениям (архив)'), ('periodic_certificates', 'Удостоверения по ОТ (один файл)'), ('periodic_certificates_by_sub', 'Удостоверения по ОТ по подразделениям (архив)'), ('ot_card_bulk', 'Личные карточки по ОТ (архив)'), ('instruction_journal_unified', 'Журнал инструктажей (один файл)'), ('instruction_journal_by_sub', 'Журнал инструктажей по подразделениям (архив)'), ('siz_cards_bulk', 'Карточки СИЗ по подразделениям (архив)'), ('siz_cards_org', 'Карточки СИЗ по организации (архив)'), ('admin_hiring_generate', 'Документы приёма из админки (архив)')], max_length=64, verbose_name='Тип задачи'),
        ),
    ]
