# Generated by Django 5.0.14 on 2026-07-07 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0082_add_height_safety_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='marked_for_deletion_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_employees', to=settings.AUTH_USER_MODEL, verbose_name='Кто отправил в архив'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marked_for_deletion',
            field=models.BooleanField(db_index=True, default=False, help_text='Сотрудник скрыт из рабочих разделов и админ-дерева, но сохранён в базе', verbose_name='В архиве'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marked_for_deletion_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки в архив'),
        ),
        migrations.AlterField(
            model_name='position',
            name='height_group_1',
            field=models.BooleanField(default=False, verbose_name='🪜 Группа 1 (работа на высоте)'),
        ),
        migrations.AlterField(
            model_name='position',
            name='height_group_2',
            field=models.BooleanField(default=False, verbose_name='🪜 Группа 2 (работа на высоте)'),
        ),
        migrations.AlterField(
            model_name='position',
            name='height_group_3',
            field=models.BooleanField(default=False, verbose_name='🪜 Группа 3 (работа на высоте)'),
        ),
    ]
