# Generated by Django 5.0.14 on 2026-10-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0083_add_employee_archived_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='conducts_introductory_briefing',
            field=models.BooleanField(default=False, help_text='Должность и ФИО такого сотрудника подставляются в п. 8 личной карточки', verbose_name='Проводит вводный инструктаж'),
        ),
    ]
